### ISSUE TITLE
Visa takes much longer than device timeout to give error

### ISSUE THREAD

**Issue by roboguy222** [pyvisa/pyvisa#213]
If an instrument is turned off and then queried, I would expect it to error out after the timeout set for that instrument.  It seems, however, that no errors are thrown until around 30 seconds later, when I get the following error.  What is going on here?

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pyvisa\resources\messagebased.py", line 40
1, in query
    self.write(message)
  File "C:\Python27\lib\site-packages\pyvisa\resources\messagebased.py", line 20
7, in write
    count = self.write_raw(message.encode(enco))
  File "C:\Python27\lib\site-packages\pyvisa\resources\messagebased.py", line 18
5, in write_raw
    return self.visalib.write(self.session, message)
  File "C:\Python27\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1864,
 in write
    ret = library.viWrite(session, data, len(data), byref(return_count))
  File "C:\Python27\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 188,
in _return_handler
    raise errors.VisaIOError(ret_value)
pyvisa.errors.VisaIOError: VI_ERROR_NLISTENERS (-1073807265): No listeners condi
tion is detected (both NRFD and NDAC are deasserted).
```

**Comment by MatthieuDartiailh** [comment]
I guess this is because VISA is confused because the resource disappeared from under it. 
Closing, feel free to re-open if there is more to discuss
