### ISSUE TITLE
pyvisa-py Error:  Could not open VISA library

### ISSUE THREAD

**Issue by wsande** [pyvisa/pyvisa#258]
I'm trying to use pyvisa with the pyvisa-py backend.  (Great, idea, BTW!)

I'm getting "OSError: Could not open VISA library:"

Code and out put (with traceback) are below.  Output of 'python -m visa info' is here:

```
C:\Python27\Scripts>python -m visa info
Machine Details:
   Platform ID:    Windows-7-6.1.7601-SP1
   Processor:      Intel64 Family 6 Model 61 Stepping 4, GenuineIntel

Python:
   Implementation: CPython
   Executable:     C:\Python27\python.exe
   Version:        2.7.10
   Compiler:       MSC v.1500 32 bit (Intel)
   Bits:           32bit
   Build:          May 23 2015 09:40:32 (#default)
   Unicode:        UCS2

PyVISA Version: 1.8

Backends:
   ni:
      Version: 1.8 (bundled with PyVISA)
      Binary library: Not found
   py:
      Version: 0.3.dev0
      ASRL INSTR:
         Please install PySerial to use this resource type.
         No module named serial
      TCPIP INSTR: Available
      USB RAW:
         Please install PyUSB to use this resource type.
         No module named usb
      USB INSTR:
         Please install PyUSB to use this resource type.
         No module named usb
      GPIB INSTR:
         Please install linux-gpib to use this resource type.
         No module named gpib
      TCPIP SOCKET: Available
```

```
import visa
visa.log_to_screen()
rm = visa.ResourceManager('@py')
rm.list_resources

```

```
>>> 
2017-03-03 09:35:35,627 - pyvisa - DEBUG - SerialSession was not imported No module named serial.
2017-03-03 09:35:35,627 - pyvisa - DEBUG - SerialSession was not imported No module named serial.
2017-03-03 09:35:35,627 - pyvisa - DEBUG - SerialSession was not imported No module named serial.
2017-03-03 09:35:35,627 - pyvisa - DEBUG - SerialSession was not imported No module named serial.
2017-03-03 09:35:35,642 - pyvisa - DEBUG - USBSession and USBRawSession were not imported No module named usb.
2017-03-03 09:35:35,642 - pyvisa - DEBUG - USBSession and USBRawSession were not imported No module named usb.
2017-03-03 09:35:35,642 - pyvisa - DEBUG - USBSession and USBRawSession were not imported No module named usb.
2017-03-03 09:35:35,642 - pyvisa - DEBUG - USBSession and USBRawSession were not imported No module named usb.
2017-03-03 09:35:35,671 - pyvisa - DEBUG - TCPIPSession was correctly imported.
2017-03-03 09:35:35,671 - pyvisa - DEBUG - TCPIPSession was correctly imported.
2017-03-03 09:35:35,671 - pyvisa - DEBUG - TCPIPSession was correctly imported.
2017-03-03 09:35:35,671 - pyvisa - DEBUG - TCPIPSession was correctly imported.
2017-03-03 09:35:35,691 - pyvisa - DEBUG - GPIBSession was not imported No module named gpib.
2017-03-03 09:35:35,691 - pyvisa - DEBUG - GPIBSession was not imported No module named gpib.
2017-03-03 09:35:35,691 - pyvisa - DEBUG - GPIBSession was not imported No module named gpib.
2017-03-03 09:35:35,691 - pyvisa - DEBUG - GPIBSession was not imported No module named gpib.
2017-03-03 09:35:35,711 - pyvisa - DEBUG - Created library wrapper for unset
2017-03-03 09:35:35,711 - pyvisa - DEBUG - Created library wrapper for unset
2017-03-03 09:35:35,711 - pyvisa - DEBUG - Created library wrapper for unset
2017-03-03 09:35:35,711 - pyvisa - DEBUG - Created library wrapper for unset
2017-03-03 09:35:35,732 - pyvisa - DEBUG - Created ResourceManager with session 2061361
2017-03-03 09:35:35,732 - pyvisa - DEBUG - Created ResourceManager with session 2061361
2017-03-03 09:35:35,732 - pyvisa - DEBUG - Created ResourceManager with session 2061361
2017-03-03 09:35:35,732 - pyvisa - DEBUG - Created ResourceManager with session 2061361
2017-03-03 09:35:36,792 - pyvisa - DEBUG - No user defined library files
2017-03-03 09:35:36,792 - pyvisa - DEBUG - No user defined library files
2017-03-03 09:35:36,792 - pyvisa - DEBUG - No user defined library files
2017-03-03 09:35:36,792 - pyvisa - DEBUG - No user defined library files
2017-03-03 09:35:36,819 - pyvisa - DEBUG - Automatically found library files: []
2017-03-03 09:35:36,819 - pyvisa - DEBUG - Automatically found library files: []
2017-03-03 09:35:36,819 - pyvisa - DEBUG - Automatically found library files: []
2017-03-03 09:35:36,819 - pyvisa - DEBUG - Automatically found library files: []
2017-03-03 09:35:36,842 - pyvisa - DEBUG - Could not open VISA wrapper <class 'pyvisa.ctwrapper.highlevel.NIVisaLibrary'>: 
Could not open VISA library:

2017-03-03 09:35:36,842 - pyvisa - DEBUG - Could not open VISA wrapper <class 'pyvisa.ctwrapper.highlevel.NIVisaLibrary'>: 
Could not open VISA library:

2017-03-03 09:35:36,842 - pyvisa - DEBUG - Could not open VISA wrapper <class 'pyvisa.ctwrapper.highlevel.NIVisaLibrary'>: 
Could not open VISA library:

2017-03-03 09:35:36,842 - pyvisa - DEBUG - Could not open VISA wrapper <class 'pyvisa.ctwrapper.highlevel.NIVisaLibrary'>: 
Could not open VISA library:

Traceback (most recent call last):
  File "<string>", line 254, in run_nodebug
  File "C:\Users\WSande\Documents\Scripts\Python_Scripts\FW_test\chamber_control_test.py", line 14, in <module>
    my_chamber = T2800Chamber('TCPIP::10.100.57.216:8888')
  File "C:\Users\WSande\Documents\Scripts\Python_Scripts\FW_test\VISA.py", line 37, in __init__
    rm = visa.ResourceManager()
  File "C:\Python27\lib\site-packages\pyvisa\highlevel.py", line 1488, in __new__
    visa_library = open_visa_library(visa_library)
  File "C:\Python27\lib\site-packages\pyvisa\highlevel.py", line 1460, in open_visa_library
    return cls(argument)
  File "C:\Python27\lib\site-packages\pyvisa\highlevel.py", line 96, in __new__
    raise OSError('Could not open VISA library:\n' + '\n'.join(errs))
OSError: Could not open VISA library:
```

**Comment by MatthieuDartiailh** [comment]
Your issue is that the ResourceManger is not specified to use the py backend when you create it. Currently PyVISA does not fall back to it automatically.
