### ISSUE TITLE
ResourceManager Garbage collection issue

### ISSUE THREAD

**Issue by alexforencich** [pyvisa/pyvisa#273]
Under some circumstances, the garbage collector will delete the ResourceManager object before the Resource objects, resulting in `pyvisa.errors.VisaIOError` exceptions from the Resource instance `__del__` methods.  

Test case:

    #/usr/bin/env python
    
    import visa
    visa.log_to_screen()
    
    rm = visa.ResourceManager()
    psu1 = rm.open_resource('visa://192.168.0.1/GPIB0::8::INSTR')
    print(psu1.ask("*IDN?"))
    
    # emulate garbage collection ordering issue
    rm.close()

Log:

    2017-07-18 10:04:04,256 - pyvisa - DEBUG - No user defined library files
    2017-07-18 10:04:04,642 - pyvisa - DEBUG - Automatically found library files: ['/usr/local/vxipnp/linux/lib64/libvisa.so']
    2017-07-18 10:04:04,654 - pyvisa - DEBUG - Library signatures: 90 ok, 0 failed
    2017-07-18 10:04:04,655 - pyvisa - DEBUG - Created library wrapper for /usr/local/vxipnp/linux/lib64/libvisa.so
    2017-07-18 10:04:04,666 - pyvisa - DEBUG - viOpenDefaultRM('<ViObject object at 0x7f22657dcd08>',) -> 0
    2017-07-18 10:04:04,666 - pyvisa - DEBUG - Created ResourceManager with session 4097
    2017-07-18 10:04:04,674 - pyvisa - DEBUG - viParseRsrcEx(4097, 'visa://192.168.0.1/GPIB0::8::INSTR', 'c_ushort(1)', 'c_ushort(0)', <ctypes.c_char_Array_256 object at 0x7f22640ed840>, <ctypes.c_char_Array_256 object at 0x7f22640ed8c8>, <ctypes.c_char_Array_256 object at 0x7f22640ed950>) -> 0
    2017-07-18 10:04:04,674 - pyvisa - DEBUG - visa://192.168.0.1/GPIB0::8::INSTR - opening ...
    2017-07-18 10:04:04,687 - pyvisa - DEBUG - viOpen(4097, 'visa://192.168.0.1/GPIB0::8::INSTR', <AccessModes.no_lock: 0>, 0, '<ViObject object at 0x7f2264376f28>') -> 0
    2017-07-18 10:04:04,687 - pyvisa - DEBUG - visa://192.168.0.1/GPIB0::8::INSTR - is open with session 1
    2017-07-18 10:04:04,689 - pyvisa - DEBUG - viWrite(1, b'*IDN?\r\n', 7, 'c_uint(7)') -> 0
    2017-07-18 10:04:04,689 - pyvisa - DEBUG - visa://192.168.0.1/GPIB0::8::INSTR - reading 20480 bytes (last status <StatusCode.success_max_count_read: 1073676294>)
    2017-07-18 10:04:04,757 - pyvisa - DEBUG - viRead(1, <ctypes.c_char_Array_20480 object at 0x7f22657dcd08>, 20480, 'c_uint(37)') -> 0
    HEWLETT-PACKARD,E3631A,0,1.2-5.0-1.0

    2017-07-18 10:04:04,758 - pyvisa - DEBUG - Closing ResourceManager (session: 4097)
    2017-07-18 10:04:04,759 - pyvisa - DEBUG - viClose(4097,) -> 0
    2017-07-18 10:04:04,773 - pyvisa - DEBUG - visa://192.168.0.1/GPIB0::8::INSTR - closing
    2017-07-18 10:04:04,773 - pyvisa - DEBUG - viDisableEvent(1, 1073709055, 65535) -> -1073807346
    Exception ignored in: 2017-07-18 10:04:04,773 - pyvisa - DEBUG - viGetAttribute(1, 3221159938, <ctypes.c_char_Array_256 object at 0x7f226688b488>) -> -1073807346
    <object repr() failed>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/site-packages/PyVISA-1.9.dev0-py3.5.egg/pyvisa/resources/resource.py", line 108, in __del__
        self.close()
      File "/usr/local/lib/python3.5/site-packages/PyVISA-1.9.dev0-py3.5.egg/pyvisa/resources/resource.py", line 237, in close
        self.before_close()
      File "/usr/local/lib/python3.5/site-packages/PyVISA-1.9.dev0-py3.5.egg/pyvisa/resources/resource.py", line 229, in before_close
        self.__switch_events_off()
      File "/usr/local/lib/python3.5/site-packages/PyVISA-1.9.dev0-py3.5.egg/pyvisa/resources/resource.py", line 246, in __switch_events_off
        self.disable_event(constants.VI_ALL_ENABLED_EVENTS, constants.VI_ALL_MECH)
      File "/usr/local/lib/python3.5/site-packages/PyVISA-1.9.dev0-py3.5.egg/pyvisa/resources/resource.py", line 301, in disable_event
        self.visalib.disable_event(self.session, event_type, mechanism)
      File "/usr/local/lib/python3.5/site-packages/PyVISA-1.9.dev0-py3.5.egg/pyvisa/ctwrapper/functions.py", line 408, in disable_event
        return library.viDisableEvent(session, event_type, mechanism)
      File "/usr/local/lib/python3.5/site-packages/PyVISA-1.9.dev0-py3.5.egg/pyvisa/ctwrapper/highlevel.py", line 188, in _return_handler
        raise errors.VisaIOError(ret_value)
    pyvisa.errors.VisaIOError: VI_ERROR_INV_OBJECT (-1073807346): The given session or object reference is invalid.

**Comment by MatthieuDartiailh** [comment]
To fix this issue, we can either skip the logic in \_\_del\_\_ (but this is not very clean) or make the ResourceManager capable of closing resources. As the resource manager does not keep references to opened resources it is possible currently but the resource manager could keep a WeakSet of opened resources and close them when it is closed. 
Opinions @thliebig @hgrecco

**Comment by hgrecco** [comment]
I like the WeakSet idea but it will still raise an error if `psu1` method (in the given example) is called. 
`ps1` outlives the `rm` and that is not something that can be fixed from inside the library.

**Comment by MatthieuDartiailh** [comment]
No but would get a nice error message explaining that the resource is closed (and we could point to the fact it may as a result of the ResourceManager destruction).

**Comment by jshnaidman** [comment]
I'm getting this issue as well. 

I created a module that creates the resource manager in the module's namespace. When I import the names from that namespace into my script (from module import *), the resource manager always errors out at the end of the script:

2018-08-10 10:35:11,277 - pyvisa - DEBUG - Closing ResourceManager (session: 4097)
2018-08-10 10:35:11,281 - pyvisa - DEBUG - viClose(4097,) -> 0
2018-08-10 10:35:11,310 - pyvisa - DEBUG - TCPIP::10.120.73.105::INSTR - closing
2018-08-10 10:35:11,310 - pyvisa - DEBUG - viDisableEvent(1, 1073709055, 65535) -> -1073807346
Exception ignored in: <function Resource.__del__ at 0x000001BDF007EAE8>
Traceback (most recent call last):
  File "***\Python37\lib\site-packages\pyvisa\resources\resource.py", line 108, in __del__
  File "***\Python37\lib\site-packages\pyvisa\resources\resource.py", line 243, in close
  File "***\Python37\lib\site-packages\pyvisa\resources\resource.py", line 235, in before_close
  File "***\Python37\lib\site-packages\pyvisa\resources\resource.py", line 252, in __switch_events_off
  File "***\Python37\lib\site-packages\pyvisa\resources\resource.py", line 309, in disable_event
  File "***\Python37\lib\site-packages\pyvisa\ctwrapper\functions.py", line 410, in disable_event
  File "***\Python37\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 188, in _return_handler
pyvisa.errors.VisaIOError: VI_ERROR_INV_OBJECT (-1073807346): The given session or object reference is invalid.

The only way for me to avoid this is to first import visa and initialize the resource manager in my own namespace first.

**Comment by MatthieuDartiailh** [comment]
I never got a chance to implement the WeakSet idea. To avoid this issue you should make sure all resources are closed at the end of the script, either by explicitely calling close or using a context manager (with statement).

**Comment by jshnaidman** [comment]
Thanks for the quick reply. That fixes it.
