### ISSUE TITLE
Exception pyvisa.errors.VisaIOError: VisaIOError(u'VI_ERROR_INV_OBJECT (-1073807346))

### ISSUE THREAD

**Issue by j5shi** [pyvisa/pyvisa#33]
Today I updated to the latest Pyvisa 1.5.dev3, however, I got this exception every time the script is finished,  by finished, I mean the following exception occurs only once no matter how many commands were sent to the instrument, which means, the exception is not thrown inside the write or read methods, but probably when the script is about to quit. for example, I asked "*IDN?" twice and quit, as a result I got the identities of the instrument twice and an exception at the end. Did anyone know the solution?

```
Rohde&Schwarz,FSV-3,1307.9002K03/101699,2.10
Rohde&Schwarz,FSV-3,1307.9002K03/101699,2.10
Exception pyvisa.errors.VisaIOError: VisaIOError(u'VI_ERROR_INV_OBJECT (-1073807346): The given session or object reference is invalid.',) in  ignored
Hit any key to close this window...
```

Here's the debug info:

```
Machine Details:
Platform ID:    Windows-7-6.1.7601-SP1
Processor:      Intel64 Family 6 Model 37 Stepping 5, GenuineIntel

Python:
Implementation: CPython
Executable:     c:\python27\python.exe
Version:        2.7.6
Compiler:       MSC v.1500 32 bit (Intel)
Bits:           32bit
Build:          Nov 10 2013 19:24:18 (#default)
Unicode:        UCS2

VISA:
#1: C:\Windows\system32\visa32.dll
found by: auto
32bit: True
64bit: False
```

**Comment by antoinebelley** [comment]
Hi I've had the same error while using PyVisa. The weirdest thing is that it works fine when I use Spyder as my text editor but if I use the terminal or another text editor like Sublime the error appears again. I've verified and they have the same path for the library. Also,the error appears only when I call the visa functions inside another function.

**Comment by gnbl** [comment]
@antoinebelley You need to provide more information, e.g. https://www.google.com/search?oq=how+to+write+a+good+bug+report

**Comment by antoinebelley** [comment]
I manage to solve it by specifying to use pyvisa-py, still not sure what the bug was about but it works now

**Comment by jugge83** [comment]
After some digging I feel like a clarification is required, I managed to get the same error (VI_ERROR_INV_OBJECT) using the visa library  (executing a standalone script). The error originates from when the visa library is called to close the session twice. The way to avoid this error was to close all instruments manually as gnbl noted. The call that caused my error was the __del__ destructor in the resourcemanager. I guess that it overloaded the destructor in the resource class or that the resource passed the wrong reference to the visa library.

**Comment by MatthieuDartiailh** [comment]
Could you check if #357 fix the issue ? With that fix, all resources are guaranteed to be closed before the ResourceManager.

**Comment by MatthieuDartiailh** [comment]
@jugge83 could you post your script ? And if you can, try not master but the branch of #357.

**Comment by MatthieuDartiailh** [comment]
This is exactly the kind of issue #357 is meant to fix. Try to uninstall pyvisa (`conda remove pyvisa`), and then re-install using the following `pip install https://github.com/pyvisa/pyvisa/tarball/rm-weakset`). 
I never had time to properly test #357 so I would be happy to have your feedback.

**Comment by kgmuzungu** [comment]
similar problem here. I use the latest NI visa (19.5), 
pip install pivisa

and I try to connect to a Rigol DP832

I can set values, so connection is fine. Only when my python script terminates I get the error. Pls see debug logging below. I havnt looked into it how to fix it. 

```
2020-01-15 19:06:25,496 - pyvisa - DEBUG - No visa library specified, trying to find alternatives.
2020-01-15 19:06:25,496 - pyvisa - DEBUG - Environment variable PYVISA_LIBRARY is unset.
2020-01-15 19:06:25,507 - pyvisa - DEBUG - Automatically found library files: [None, 'C:\\WINDOWS\\system32\\visa32.dll', 'C:\\WINDOWS\\system32\\visa32.dll', 'C:\\WINDOWS\\system32\\visa64.dll', 'C:\\WINDOWS\\system32\\visa64.dll']
2020-01-15 19:06:25,507 - pyvisa - DEBUG - No user defined library files
2020-01-15 19:06:25,507 - pyvisa - DEBUG - The NI implementation available
2020-01-15 19:06:25,528 - pyvisa - DEBUG - Automatically found library files: [None, 'C:\\WINDOWS\\system32\\visa32.dll', 'C:\\WINDOWS\\system32\\visa32.dll', 'C:\\WINDOWS\\system32\\visa64.dll', 'C:\\WINDOWS\\system32\\visa64.dll']
2020-01-15 19:06:25,529 - pyvisa - DEBUG - No user defined library files
2020-01-15 19:06:25,534 - pyvisa - DEBUG - Library signatures: 90 ok, 0 failed
2020-01-15 19:06:25,534 - pyvisa - DEBUG - Created library wrapper for C:\WINDOWS\system32\visa32.dll
2020-01-15 19:06:25,598 - pyvisa - DEBUG - viOpenDefaultRM('<ViObject object at 0x000001B3516C6540>',) -> 0
2020-01-15 19:06:25,598 - pyvisa - DEBUG - Created ResourceManager with session 4097
('USB0::0x1AB1::0x0E11::DP8C173503852::INSTR', 'ASRL5::INSTR', 'ASRL6::INSTR', 'ASRL7::INSTR', 'ASRL8::INSTR', 'ASRL10::INSTR')
['USB0::0x1AB1::0x0E11::DP8C173503852::INSTR']
2020-01-15 19:06:25,800 - pyvisa - DEBUG - viFindRsrc(4097, '?*::INSTR', '<ViObject object at 0x000001B3516C6540>', 'c_ulong(6)', <ctypes.c_char_Array_256 object at 0x000001B3516C65C0>) -> 0
2020-01-15 19:06:25,800 - pyvisa - DEBUG - viFindNext(<ViObject object at 0x000001B3516C6540>, <ctypes.c_char_Array_256 object at 0x000001B3516C65C0>) -> 0
2020-01-15 19:06:25,800 - pyvisa - DEBUG - viFindNext(<ViObject object at 0x000001B3516C6540>, <ctypes.c_char_Array_256 object at 0x000001B3516C65C0>) -> 0
2020-01-15 19:06:25,800 - pyvisa - DEBUG - viFindNext(<ViObject object at 0x000001B3516C6540>, <ctypes.c_char_Array_256 object at 0x000001B3516C65C0>) -> 0
2020-01-15 19:06:25,800 - pyvisa - DEBUG - viFindNext(<ViObject object at 0x000001B3516C6540>, <ctypes.c_char_Array_256 object at 0x000001B3516C65C0>) -> 0
2020-01-15 19:06:25,800 - pyvisa - DEBUG - viFindNext(<ViObject object at 0x000001B3516C6540>, <ctypes.c_char_Array_256 object at 0x000001B3516C65C0>) -> 0
2020-01-15 19:06:25,800 - pyvisa - DEBUG - viClose(<ViObject object at 0x000001B3516C6540>,) -> 0
2020-01-15 19:06:25,804 - pyvisa - DEBUG - viFindRsrc(4097, '?*::INSTR', '<ViObject object at 0x000001B351662AC0>', 'c_ulong(6)', <ctypes.c_char_Array_256 object at 0x000001B3516C65C0>) -> 0
2020-01-15 19:06:25,804 - pyvisa - DEBUG - viFindNext(<ViObject object at 0x000001B351662AC0>, <ctypes.c_char_Array_256 object at 0x000001B3516C65C0>) -> 0
2020-01-15 19:06:25,804 - pyvisa - DEBUG - viFindNext(<ViObject object at 0x000001B351662AC0>, <ctypes.c_char_Array_256 object at 0x000001B3516C65C0>) -> 0
2020-01-15 19:06:25,804 - pyvisa - DEBUG - viFindNext(<ViObject object at 0x000001B351662AC0>, <ctypes.c_char_Array_256 object at 0x000001B3516C65C0>) -> 0
2020-01-15 19:06:25,804 - pyvisa - DEBUG - viFindNext(<ViObject object at 0x000001B351662AC0>, <ctypes.c_char_Array_256 object at 0x000001B3516C65C0>) -> 0
2020-01-15 19:06:25,804 - pyvisa - DEBUG - viFindNext(<ViObject object at 0x000001B351662AC0>, <ctypes.c_char_Array_256 object at 0x000001B3516C65C0>) -> 0
2020-01-15 19:06:25,804 - pyvisa - DEBUG - viClose(<ViObject object at 0x000001B351662AC0>,) -> 0
2020-01-15 19:06:25,804 - pyvisa - DEBUG - viParseRsrcEx(4097, 'USB0::0x1AB1::0x0E11::DP8C173503852::INSTR', 'c_ushort(7)', 'c_ushort(0)', <ctypes.c_char_Array_256 object at 0x000001B3516C65C0>, <ctypes.c_char_Array_256 object at 0x000001B3516C6540>, <ctypes.c_char_Array_256 object at 0x000001B3516C64C0>) -> 0
2020-01-15 19:06:25,804 - pyvisa - DEBUG - USB0::0x1AB1::0x0E11::DP8C173503852::INSTR - opening ...
device: USBInstrument at USB0::0x1AB1::0x0E11::DP8C173503852::INSTR
Connected
2020-01-15 19:06:25,809 - pyvisa - DEBUG - viOpen(4097, 'USB0::0x1AB1::0x0E11::DP8C173503852::INSTR', <AccessModes.no_lock: 0>, 0, '<ViObject object at 0x000001B3522A5DC0>') -> 0
2020-01-15 19:06:25,809 - pyvisa - DEBUG - USB0::0x1AB1::0x0E11::DP8C173503852::INSTR - is open with session 1
2020-01-15 19:06:25,809 - pyvisa - DEBUG - viWrite(1, b':INST:NSEL 1\r\n', 14, 'c_ulong(14)') -> 0
2020-01-15 19:06:25,822 - pyvisa - DEBUG - viWrite(1, b':VOLT 11\r\n', 10, 'c_ulong(10)') -> 0
2020-01-15 19:06:25,838 - pyvisa - DEBUG - Closing ResourceManager (session: 4097)
2020-01-15 19:06:25,846 - pyvisa - DEBUG - viClose(4097,) -> 0
2020-01-15 19:06:25,846 - pyvisa - DEBUG - USB0::0x1AB1::0x0E11::DP8C173503852::INSTR - closing
2020-01-15 19:06:25,847 - pyvisa - DEBUG - viDisableEvent(1, 1073709055, 65535) -> -1073807346
Exception ignored in: <function Resource.__del__ at 0x000001B35164FA60>
Traceback (most recent call last):
  File "C:\Users\kg-mimi-lapt\PythonProjects\controllingDP832\venv\lib\site-packages\pyvisa\resources\resource.py", line 114, in __del__
  File "C:\Users\kg-mimi-lapt\PythonProjects\controllingDP832\venv\lib\site-packages\pyvisa\resources\resource.py", line 252, in close
  File "C:\Users\kg-mimi-lapt\PythonProjects\controllingDP832\venv\lib\site-packages\pyvisa\resources\resource.py", line 244, in before_close
  File "C:\Users\kg-mimi-lapt\PythonProjects\controllingDP832\venv\lib\site-packages\pyvisa\resources\resource.py", line 261, in __switch_events_off
  File "C:\Users\kg-mimi-lapt\PythonProjects\controllingDP832\venv\lib\site-packages\pyvisa\resources\resource.py", line 318, in disable_event
  File "C:\Users\kg-mimi-lapt\PythonProjects\controllingDP832\venv\lib\site-packages\pyvisa\ctwrapper\functions.py", line 410, in disable_event
  File "C:\Users\kg-mimi-lapt\PythonProjects\controllingDP832\venv\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 193, in _return_handler
pyvisa.errors.VisaIOError: VI_ERROR_INV_OBJECT (-1073807346): The given session or object reference is invalid.
```

**Comment by MatthieuDartiailh** [comment]
Could you post the output of `pyvisa-info` ? And your script ?

**Comment by kgmuzungu** [comment]
Magic happened. After rebooting my machine, it worked like a charm. Thank you for the fast reply and sorry for the inconvenience. I still post the pyvisa-info FYI

```
(venv) C:\Users\kg-mimi-lapt\PythonProjects\controllingDP832>pyvisa-info
Machine Details:
   Platform ID:    Windows-10-10.0.18362-SP0
   Processor:      Intel64 Family 6 Model 142 Stepping 9, GenuineIntel

Python:
   Implementation: CPython
   Executable:     C:\Users\kg-mimi-lapt\PythonProjects\controllingDP832\venv\Scripts\python.exe
   Version:        3.8.0
   Compiler:       MSC v.1916 64 bit (AMD64)
   Bits:           64bit
   Build:          Oct 14 2019 19:37:50 (#tags/v3.8.0:fa919fd)
   Unicode:        UCS4

PyVISA Version: 1.10.1

Backends:
   ni:
      Version: 1.10.1 (bundled with PyVISA)
      #1: C:\WINDOWS\system32\visa32.dll:
         found by: auto
         bitness: 64
         Vendor: National Instruments
         Impl. Version: 19923456
         Spec. Version: 5244928
      #2: C:\WINDOWS\system32\visa64.dll:
         found by: auto
         bitness: 64
         Vendor: National Instruments
         Impl. Version: 19923456
         Spec. Version: 5244928

```

**Comment by kgmuzungu** [comment]
I played around a bit more. The error came back. The problem was that I didnt call 

```
rm = visa.ResourceManager()
...
rm.close()

```

Thank you for the time of all involved implementing pyvisa

**Comment by MatthieuDartiailh** [comment]
Could you post your script ? This should not happen in pyvisa 1.10 when you open resources through the resource manager.

**Comment by alexlawriewood** [comment]
I still have the same problem here.

```
(venv-eq) C:\>pyvisa-info

Machine Details:
   Platform ID:    Windows-10-10.0.17134-SP0
   Processor:      Intel64 Family 6 Model 142 Stepping 10, GenuineIntel

Python:
   Implementation: CPython
   Executable:     c:\venv\eq\scripts\python.exe
   Version:        3.6.8
   Compiler:       MSC v.1916 32 bit (Intel)
   Bits:           32bit
   Build:          Dec 23 2018 23:31:17 (#tags/v3.6.8:3c6b436a57)
   Unicode:        UCS4

PyVISA Version: 1.10.1

Backends:
   ni:
      Version: 1.10.1 (bundled with PyVISA)
      #1: C:\WINDOWS\system32\visa32.dll:
[pyvisa.log](https://github.com/pyvisa/pyvisa/files/4231585/pyvisa.log)

         found by: auto
         bitness: 32
         Vendor: National Instruments
         Impl. Version: 17827072
         Spec. Version: 5244928
```

I'm using a little Python auto-discovery script and driver; I attach the results of the pyvisa logger set to DEBUG. For what it's worth, running `IPython.embed()` seemed to start it breaking; however, it carried on breaking in every new Python interpreter after that. But could be a coincidence.

Cheers,
Alex

**Comment by MatthieuDartiailh** [comment]
I am not sure what is exactly happening but I suspect something going on with garbage collecting the resource at a wrong time. Could you try replacing https://github.com/pyvisa/pyvisa/blob/master/pyvisa/highlevel.py#L1642 by:
```python
            existing_resources = list(self._created_resources)
            for resource in existing_resources:
```

**Comment by alexlawriewood** [comment]
I suppose that's exactly the problem, because my resource's `__del__` is being called by the interpreter rather than from `highlevel.ResourceManager.close` on the line you refer to. Note the first line of the stack trace:
```
Exception ignored in: <bound method Resource.__del__ of <'USBInstrument'('USB0::0x0957::0x4707::MY53300468::INSTR')>>
Traceback (most recent call last):
  File "c:\venv\eq\lib\site-packages\pyvisa\resources\resource.py", line 114, in __del__
  File "c:\venv\eq\lib\site-packages\pyvisa\resources\resource.py", line 252, in close
  File "c:\venv\eq\lib\site-packages\pyvisa\resources\resource.py", line 244, in before_close
  File "c:\venv\eq\lib\site-packages\pyvisa\resources\resource.py", line 261, in __switch_events_off
  File "c:\venv\eq\lib\site-packages\pyvisa\resources\resource.py", line 318, in disable_event
  File "c:\venv\eq\lib\site-packages\pyvisa\ctwrapper\functions.py", line 410, in disable_event
  File "c:\venv\eq\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 193, in _return_handler
pyvisa.errors.VisaIOError: VI_ERROR_INV_OBJECT (-1073807346): The given session or object reference is invalid.
```

Isn't this normal, though? As [the Python docs describe it](https://docs.python.org/3/reference/datamodel.html#object.__del__), there aren't really any guarantees about what will still exist when a `__del__` method is run (or even that the method will be run at all). I'd be inclined to try something with [atexit](https://docs.python.org/3/library/atexit.html#module-atexit); I'm happy to propose a patch if it'd be useful?

**Comment by MatthieuDartiailh** [comment]
The trouble I have with atexit is that it delays the cleanup of the ResourceManager to the interpreter shutdown if used naively which is fine for a single script but more of a concern for long running applications, which is why using it for resources is not an option.
Honestly not closing your resource before the end of a script is just bad practice (resources can be used as context managers to avoid that kind of problem) and in larger program it is also easy to avoid.
All that said we could try to do something with an atexit handler using only a weakref so that it does not keep the ResourceManager alive for no reason. I am not sure that would fix the issue because we may still have some weird interaction between atexit and the gc but it may be worth trying.

**Comment by jugge83** [comment]
Since I'm not the only one experiencing this I'm posting a bare bone version of my solution to the issue:

```python
import pyvisa

def log(*args, **kwargs):
    pass#print(*args, **kwargs)

class Instrument:
    def __init__(self, adress = 'GPIB0::2::INSTR'):
        self.rm, self.inst = self.get_inst(adress)

    def get_inst(self, adress):
        rm = pyvisa.ResourceManager()
        res = rm.list_resources()
        log(res)
        inst = rm.open_resource(adress)
        return rm, inst

    def __del__(self): 
        self.inst.close()
        self.rm.close()

if __name__ == '__main__':
    inst = Instrument()
    #do stuff
    del inst
```

**Comment by alexlawriewood** [comment]
> Honestly not closing your resource before the end of a script is just bad practice (resources can be used as context managers to avoid that kind of problem) and in larger program it is also easy to avoid.

Ah! Okay, I honestly hadn't understood that from the documentation; none of the examples seem to do it. Combined with the fact that there was an open issue around it, I just assumed (seems silly in hindsight!) that the VISA backend did any necessary tidying up once pyvisa had stopped.

> All that said we could try to do something with an atexit handler using only a weakref so that it does not keep the ResourceManager alive for no reason. I am not sure that would fix the issue because we may still have some weird interaction between atexit and the gc but it may be worth trying.

Yeah, the documentation on atexit isn't crystal clear on the order there. It'd make sense to me that atexit handlers would be registered before any of the interpreter 'stopping', but maybe not.

I'll have a play around; guess I'm welcome to propose additions to the documentation too?
