### ISSUE TITLE
Can't connect to PSU

### ISSUE THREAD

**Issue by kieranobrien** [pyvisa/pyvisa#362]
Hi,

I hope you can help, I am having trouble connecting to a power supply. I have searched around and can't find anything obvious, but I have not used pyvisa in the past.

On the NI VISA Test Panel it works fine;

1: Write Operation (*IDN?\n)

Return Count: 6 bytes

2: Read Operation
Return Count: 36 bytes
NPD3XHB4160027,1.01.01.02.02R2,V3.0\n

On Pyvisa (same if it is visa not pyvisa);

import pyvisa
rm = pyvisa.ResourceManager()
inst = rm.open_resource('USB0::0x0483::0x7540::NPD3XHB4160027::INSTR')
inst.query('*IDN?')

It gets a timeout with the message;

Traceback (most recent call last):
  File "E:/PycharmProjects/serial/Py_visa_example.py", line 4, in <module>
    inst.query('*IDN?')
  File "C:\Anaconda2\lib\site-packages\pyvisa\resources\messagebased.py", line 569, in query
    return self.read()
  File "C:\Anaconda2\lib\site-packages\pyvisa\resources\messagebased.py", line 413, in read
    message = self._read_raw().decode(enco)
  File "C:\Anaconda2\lib\site-packages\pyvisa\resources\messagebased.py", line 386, in _read_raw
    chunk, status = self.visalib.read(self.session, size)
  File "C:\Anaconda2\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1584, in read
    ret = library.viRead(session, buffer, count, byref(return_count))
  File "C:\Anaconda2\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 188, in _return_handler
    raise errors.VisaIOError(ret_value)
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.

The output from "python -m visa info" is 

Machine Details:
   Platform ID:    Windows-10-10.0.10240
   Processor:      Intel64 Family 6 Model 94 Stepping 3, GenuineIntel

Python:
   Implementation: CPython
   Executable:     C:\Anaconda2\python.exe
   Version:        2.7.12
   Compiler:       MSC v.1500 64 bit (AMD64)
   Bits:           64bit
   Build:          Jun 29 2016 11:07:13 (#default)
   Unicode:        UCS2

PyVISA Version: 1.8

Backends:
   ni:
      Version: 1.8 (bundled with PyVISA)
      #1: C:\Windows\system32\visa32.dll:
         found by: auto
         bitness: 64
         Vendor: National Instruments
         Impl. Version: 15728640
         Spec. Version: 5243904
      #2: C:\Windows\system32\visa64.dll:
         found by: auto
         bitness: 64
         Vendor: National Instruments
         Impl. Version: 15728640
         Spec. Version: 5243904

**Comment by MatthieuDartiailh** [comment]
It looks like a termination character issue. Look at your instrument manual or at what Ni is using and set the proper value for `read_termination` and `write_termination`. Since the message you got in Ni ends with `\n`, try:
```python
inst.read_termination = '\n'
insr.write_termination = '\n'
```

**Comment by kieranobrien** [comment]
Hi Mathieu, thanks for taking a look at this.

 I should have said that that I had tried that without success. I tried '\n', '\r' and '\r\n'. 

I included the log_to_screen and here is the output. 

2018-09-27 13:11:44,924 - pyvisa - DEBUG - No visa library specified, trying to find alternatives.
2018-09-27 13:11:44,924 - pyvisa - DEBUG - Environment variable PYVISA_LIBRARY is unset.
2018-09-27 13:11:44,944 - pyvisa - DEBUG - No user defined library files
2018-09-27 13:11:44,944 - pyvisa - DEBUG - Automatically found library files: ['C:\\Windows\\system32\\visa32.dll', 'C:\\Windows\\system32\\visa64.dll']
2018-09-27 13:11:44,944 - pyvisa - DEBUG - The NI implementation available
2018-09-27 13:11:44,944 - pyvisa - DEBUG - No user defined library files
2018-09-27 13:11:44,944 - pyvisa - DEBUG - Automatically found library files: ['C:\\Windows\\system32\\visa32.dll', 'C:\\Windows\\system32\\visa64.dll']
2018-09-27 13:11:44,944 - pyvisa - DEBUG - Library signatures: 90 ok, 0 failed
2018-09-27 13:11:44,944 - pyvisa - DEBUG - Created library wrapper for C:\Windows\system32\visa32.dll
2018-09-27 13:11:44,963 - pyvisa - DEBUG - viOpenDefaultRM('<ViObject object at 0x0000000003C3D0C8>',) -> 0
2018-09-27 13:11:44,973 - pyvisa - DEBUG - Created ResourceManager with session 4097
2018-09-27 13:11:44,973 - pyvisa - DEBUG - viParseRsrcEx(4097L, 'USB0::0x0483::0x7540::NPD3XHB4160027::INSTR', 'c_ushort(7)', 'c_ushort(0)', <ctypes.c_char_Array_256 object at 0x0000000003C3D548>, <ctypes.c_char_Array_256 object at 0x0000000003C3D6C8>, <ctypes.c_char_Array_256 object at 0x0000000003C3D7C8>) -> 0
2018-09-27 13:11:44,973 - pyvisa - DEBUG - USB0::0x0483::0x7540::NPD3XHB4160027::INSTR - opening ...
2018-09-27 13:11:44,973 - pyvisa - DEBUG - viOpen(4097L, 'USB0::0x0483::0x7540::NPD3XHB4160027::INSTR', <AccessModes.no_lock: 0>, 0, '<ViObject object at 0x0000000003C3D7C8>') -> 0
2018-09-27 13:11:44,973 - pyvisa - DEBUG - USB0::0x0483::0x7540::NPD3XHB4160027::INSTR - is open with session 1
2018-09-27 13:11:44,973 - pyvisa - DEBUG - viSetAttribute(1L, 1073676312, 10) -> 0
2018-09-27 13:11:44,983 - pyvisa - DEBUG - viSetAttribute(1L, 1073676344, 1) -> 0
2018-09-27 13:11:44,983 - pyvisa - DEBUG - viWrite(1L, '*IDN?\r\n', 7, 'c_ulong(7L)') -> 0
2018-09-27 13:11:44,983 - pyvisa - DEBUG - USB0::0x0483::0x7540::NPD3XHB4160027::INSTR - reading 20480 bytes (last status <StatusCode.success_max_count_read: 1073676294>)
2018-09-27 13:13:46,990 - pyvisa - DEBUG - viRead(1L, <ctypes.c_char_Array_20480 object at 0x0000000003C3D7C8>, 20480, 'c_ulong(0L)') -> -1073807339
2018-09-27 13:13:46,990 - pyvisa - DEBUG - USB0::0x0483::0x7540::NPD3XHB4160027::INSTR - exception while reading: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.
Buffer content: bytearray(b'')
Traceback (most recent call last):
  File "E:\PycharmProjects\serial\Py_visa_example.py", line 11, in <module>
    print(inst.read())
  File "C:\Anaconda2\lib\site-packages\pyvisa\resources\messagebased.py", line 413, in read
    message = self._read_raw().decode(enco)
  File "C:\Anaconda2\lib\site-packages\pyvisa\resources\messagebased.py", line 386, in _read_raw
    chunk, status = self.visalib.read(self.session, size)
  File "C:\Anaconda2\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1584, in read
    ret = library.viRead(session, buffer, count, byref(return_count))
  File "C:\Anaconda2\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 188, in _return_handler
    raise errors.VisaIOError(ret_value)
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.
2018-09-27 13:13:47,000 - pyvisa - DEBUG - USB0::0x0483::0x7540::NPD3XHB4160027::INSTR - closing
2018-09-27 13:13:47,000 - pyvisa - DEBUG - viDisableEvent(1L, 1073709055, 65535) -> 1073676291
2018-09-27 13:13:47,009 - pyvisa - DEBUG - viDiscardEvents(1L, 1073709055, 65535) -> 1073676292
2018-09-27 13:13:47,009 - pyvisa - DEBUG - viClose(1L,) -> 0
2018-09-27 13:13:47,009 - pyvisa - DEBUG - USB0::0x0483::0x7540::NPD3XHB4160027::INSTR - is closed

**Comment by MatthieuDartiailh** [comment]
Can you try reading a byte at a time using the `read_bytes` method ? If you cannot read a single byte it probably means the instrument does not consider the instruction complete. If you can it means that there is something wrong with the read_termination detection.

**Comment by kieranobrien** [comment]
It doesn't seem to like to read even a single byte...

2018-09-28 10:24:25,196 - pyvisa - DEBUG - No visa library specified, trying to find alternatives.
2018-09-28 10:24:25,196 - pyvisa - DEBUG - Environment variable PYVISA_LIBRARY is unset.
2018-09-28 10:24:25,196 - pyvisa - DEBUG - No user defined library files
2018-09-28 10:24:25,196 - pyvisa - DEBUG - Automatically found library files: ['C:\\Windows\\system32\\visa32.dll', 'C:\\Windows\\system32\\visa64.dll']
2018-09-28 10:24:25,196 - pyvisa - DEBUG - The NI implementation available
2018-09-28 10:24:25,196 - pyvisa - DEBUG - No user defined library files
2018-09-28 10:24:25,206 - pyvisa - DEBUG - Automatically found library files: ['C:\\Windows\\system32\\visa32.dll', 'C:\\Windows\\system32\\visa64.dll']
2018-09-28 10:24:25,206 - pyvisa - DEBUG - Library signatures: 90 ok, 0 failed
2018-09-28 10:24:25,206 - pyvisa - DEBUG - Created library wrapper for C:\Windows\system32\visa32.dll
2018-09-28 10:24:25,216 - pyvisa - DEBUG - viOpenDefaultRM('<ViObject object at 0x0000000003E289C8>',) -> 0
2018-09-28 10:24:25,216 - pyvisa - DEBUG - Created ResourceManager with session 4097
2018-09-28 10:24:25,216 - pyvisa - DEBUG - viParseRsrcEx(4097L, 'USB0::0x0483::0x7540::NPD3XHB4160027::INSTR', 'c_ushort(7)', 'c_ushort(0)', <ctypes.c_char_Array_256 object at 0x0000000003EBA0C8>, <ctypes.c_char_Array_256 object at 0x0000000003EBA1C8>, <ctypes.c_char_Array_256 object at 0x0000000003EBA448>) -> 0
2018-09-28 10:24:25,216 - pyvisa - DEBUG - USB0::0x0483::0x7540::NPD3XHB4160027::INSTR - opening ...
2018-09-28 10:24:25,226 - pyvisa - DEBUG - viOpen(4097L, 'USB0::0x0483::0x7540::NPD3XHB4160027::INSTR', <AccessModes.no_lock: 0>, 0, '<ViObject object at 0x0000000003E289C8>') -> 0
2018-09-28 10:24:25,226 - pyvisa - DEBUG - USB0::0x0483::0x7540::NPD3XHB4160027::INSTR - is open with session 1
2018-09-28 10:24:25,226 - pyvisa - DEBUG - viSetAttribute(1L, 1073676312, 10) -> 0
2018-09-28 10:24:25,226 - pyvisa - DEBUG - viSetAttribute(1L, 1073676344, 1) -> 0
2018-09-28 10:24:25,226 - pyvisa - DEBUG - viWrite(1L, '*IDN?\n', 6, 'c_ulong(6L)') -> 0
2018-09-28 10:24:25,226 - pyvisa - DEBUG - USB0::0x0483::0x7540::NPD3XHB4160027::INSTR - reading 1 bytes (last status None)
2018-09-28 10:26:27,236 - pyvisa - DEBUG - viRead(1L, <ctypes.c_char_Array_1 object at 0x0000000003E289C8>, 1, 'c_ulong(0L)') -> -1073807339
2018-09-28 10:26:27,236 - pyvisa - DEBUG - USB0::0x0483::0x7540::NPD3XHB4160027::INSTR - exception while reading: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.
Buffer content: bytearray(b'')
Traceback (most recent call last):
  File "E:/PycharmProjects/serial/Py_visa_example.py", line 10, in <module>
    inst.read_bytes(1)
  File "C:\Anaconda2\lib\site-packages\pyvisa\resources\messagebased.py", line 342, in read_bytes
    chunk, status = self.visalib.read(self.session, size)
  File "C:\Anaconda2\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1584, in read
    ret = library.viRead(session, buffer, count, byref(return_count))
  File "C:\Anaconda2\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 188, in _return_handler
    raise errors.VisaIOError(ret_value)
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.
2018-09-28 10:26:27,256 - pyvisa - DEBUG - USB0::0x0483::0x7540::NPD3XHB4160027::INSTR - closing
2018-09-28 10:26:27,266 - pyvisa - DEBUG - viDisableEvent(1L, 1073709055, 65535) -> 1073676291
2018-09-28 10:26:27,266 - pyvisa - DEBUG - viDiscardEvents(1L, 1073709055, 65535) -> 1073676292
2018-09-28 10:26:27,266 - pyvisa - DEBUG - viClose(1L,) -> 0
2018-09-28 10:26:27,266 - pyvisa - DEBUG - USB0::0x0483::0x7540::NPD3XHB4160027::INSTR - is closed

Process finished with exit code 1

I have tried putting a 5 second delay into the query command, but this does not seem to make any difference. 

OK, I have managed to recreate the problem in NIMAX. If I select "TMC Vendor" for the I/O Protocol then I get the same time out error. Is there a way to set this in pyvisa?

**Comment by MatthieuDartiailh** [comment]
Ok so the fact you cannot read even a single byte probably means the instrument did not understand the input message.
What value were you using before under I/O Protocol ? Is the address you use ('USB0::0x0483::0x7540::NPD3XHB4160027::INSTR') the same as the one NI MAX use ? Does the NIMAX address ends in RAW ?

**Comment by kieranobrien** [comment]
no, they are both INSTR. On NIMAX the protocol says 'NORMAL'.

USB0::0x0483::0x7540::SPD1A134600512::INSTR

The address has now changed a bit, as I did a firmware upgrade on the PSU to see if this would help (there was a comment about connectivity on the firmware page). The PSU is a Siglent SPD3000, but it was badged as RS-PRO before the upgrade. 

The behaviour hasn't changed. The WRITE command seems to complete OK, but the following READ command is the one causing the problem.

Thanks for your help with this!

**Comment by MatthieuDartiailh** [comment]
You can try the following:
```python
print(inst.get_visa_attribute('io_protocol'))
from pyvisa.constants import IOProtocol
inst.set_visa_attribute('io_protocol', IOProtocol.normal)
```
After check all the attributes set by NI-MAX and we can try to duplicate them all.

**Comment by kieranobrien** [comment]
I get the following message...

Traceback (most recent call last):
  File "E:/PycharmProjects/serial/Py_visa_example.py", line 12, in <module>
    print(inst.get_visa_attribute(io_protocol))
NameError: name 'io_protocol' is not defined

**Comment by MatthieuDartiailh** [comment]
Sorry I keep forgetting how this method works....
You should do:
```python
from pyvisa import constants
print(inst.get_visa_attribute(constants.VI_ATTR_IO_PROT))
inst.set_visa_attribute(constants.VI_ATTR_IO_PROT, IOProtocol.normal)
```

**Comment by MatthieuDartiailh** [comment]
@wstefan20 what instrument are you trying to connect to, same as @kieranobrien ? What have you tried so far ? Can you try to use a command that should produce a visible change on the instrument to check your write ?

**Comment by wstefan20** [comment]
Sorry. I did not see your reply until now @MatthieuDartiailh . I am using the Siglent SPD3303X-E. I tried setting the constants and no change.

**Comment by MatthieuDartiailh** [comment]
Could you post the output of `pyvisa-info`, a script describing what you tried and the a screen shot of the VISA attributes as displayed in NI-MAX ? 
Also did you make sure the termination character on write operation is properly set ? The first thing to figure out is why a write command does not cause any change, we will come back to reading after.

**Comment by wstefan20** [comment]
I actually fixed the issue. Turns out that this device needs a slight delay. By adding the following code, I was able to correct any issues: 

inst.query_delay = 0.01

I was looking at older versions of the documentation which had inst.delay instead which doesn't work.

I'm just disappointed there's no mention of this issue in the manual for the device, or a note on the tutorial for PyVISA. Hope this helps someone!

**Comment by MatthieuDartiailh** [comment]
Would you consider #483 to address the issue with sufficient clarity ?

**Comment by talalk123** [comment]
> I actually fixed the issue. Turns out that this device needs a slight delay. By adding the following code, I was able to correct any issues:
> 
> inst.query_delay = 0.01
> 
> I was looking at older versions of the documentation which had inst.delay instead which doesn't work.
> 
> I'm just disappointed there's no mention of this issue in the manual for the device, or a note on the tutorial for PyVISA. Hope this helps someone!

Hi I was able to query the siglent and get the following response back:
- Siglent Technologies,SPD3303X-E,SPD3XIDX4R0926,1.01.01.02.05,V3.0

I can't however set the voltage/current using the commands, it just always beeps. Do you have any pointers for what could help?

Thanks.

**Comment by MatthieuDartiailh** [comment]
Usually an instrument beeps to signal an error. Can you check what is that error directly on the instrument ? Can you share the code you use ? maybe you made a small mistake in the command that other could spot.

**Comment by motibass** [comment]
@kieranobrien 
Had the same issue,
This resolves it :
https://siglentna.com/operating-tip/spd-programming-tips/
You have to put a delay between the commands.

**Comment by MatthieuDartiailh** [comment]
Closing this since it appears adding a delay allow the instrument to work properly.
