### ISSUE TITLE
Pyvisa Error -1073807346

### ISSUE THREAD

**Issue by sumanthraja** [pyvisa/pyvisa#381]
Hi

I am trying to build a automation module and I tried couple of methods these are the issues I am facing.

If I am trying the below method, I am getting the following errors

![thermal](https://user-images.githubusercontent.com/23439472/48808885-45ebb880-ecd7-11e8-953a-cc26037b1af1.PNG)

![automation](https://user-images.githubusercontent.com/23439472/48808890-4c7a3000-ecd7-11e8-9c98-1db570c7d8f2.PNG)

Exception ignored in: <object repr() failed>                                                                            
Traceback (most recent call last):                                                                
File "C:\Python\lib\site-packages\pyvisa\resources\resource.py", line 108, in __del__
File "C:\Python\lib\site-packages\pyvisa\resources\resource.py", line 243, in close
File "C:\Python\lib\site-packages\pyvisa\resources\resource.py", line 235, in before_close 
File "C:\Python\lib\site-packages\pyvisa\resources\resource.py", line 252, in __switch_events_off
File "C:\Python\lib\site-packages\pyvisa\resources\resource.py", line 309, in disable_event                             
File "C:\Python\lib\site-packages\pyvisa\ctwrapper\functions.py", line 410, in disable_event                           
File "C:\Python\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 188, in _return_handler                        
pyvisa.errors.VisaIOError: VI_ERROR_INV_OBJECT (-1073807346): The given session or object reference is invalid. 

But if I try the below method, the total run time is 20 sec:

![thermal1](https://user-images.githubusercontent.com/23439472/48809091-0f626d80-ecd8-11e8-936c-f199f5ff33ea.PNG)

![automation1](https://user-images.githubusercontent.com/23439472/48809093-12f5f480-ecd8-11e8-968f-608b35c49b45.PNG)

If I run directly it just takes around 10 sec to run

```python
import visa

if __name__ == '__main__':
    rm = visa.ResourceManager()
    gpibid='GPIB0::10::INSTR'
    instrument = rm.open_resource(gpibid)
    device_model = instrument.query("*IDN?")
    print(device_model)
```

Can I know why am I getting this error and why there is rise in run time when run through a another class. Let me know if you have any questions

Thanks in advance

**Comment by MatthieuDartiailh** [comment]
Could you please do the following ?
- post the output of `pyvisa-info` (or `python -m visa info`) ?
- try to explicitly close the instrument at the end of your script (by calling close) ?
- if the previous work try to install using `pip install https://github.com/pyvisa/pyvisa/tarball/rm-weakset` and check your original script works.

I have no idea why you see such a large change when you change the instantiation of the manager. I will try to think about it.

**Comment by sumanthraja** [comment]
As you asked I tried calling the `close()` function but it didn't improve anything, So I didn't try the weakset installation. Also you can find the `python -m visa info` below

<img width="275" alt="pyvisa-info" src="https://user-images.githubusercontent.com/23439472/49050301-a4151180-f197-11e8-9c3f-2f1a319ed453.PNG">

Also when I was calling the list of resources I find so many but I am using only one device, I don't understand why. How to clear the list of resources that are not being used and is that affecting it any way with respect to run time?

`import visa                                                                                                                                                                               rm = visa.ResourceManager()                                                                                                                                                              rm.list_resources()
`
Output:

`('GPIB0::10::0::INSTR', 'GPIB0::10::10::INSTR', 'GPIB0::10::11::INSTR', 'GPIB0::10::12::INSTR', 'GPIB0::10::13::INSTR', 'GPIB0::10::14::INSTR', 'GPIB0::10::15::INSTR', 'GPIB0::10::16::INSTR', 'GPIB0::10::17::INSTR', 'GPIB0::10::18::INSTR', 'GPIB0::10::19::INSTR', 'GPIB0::10::1::INSTR', 'GPIB0::10::20::INSTR', 'GPIB0::10::21::INSTR', 'GPIB0::10::22::INSTR', 'GPIB0::10::23::INSTR', 'GPIB0::10::24::INSTR', 'GPIB0::10::25::INSTR', 'GPIB0::10::26::INSTR', 'GPIB0::10::27::INSTR', 'GPIB0::10::28::INSTR', 'GPIB0::10::29::INSTR', 'GPIB0::10::2::INSTR', 'GPIB0::10::30::INSTR', 'GPIB0::10::3::INSTR', 'GPIB0::10::4::INSTR', 'GPIB0::10::5::INSTR', 'GPIB0::10::6::INSTR', 'GPIB0::10::7::INSTR', 'GPIB0::10::8::INSTR', 'GPIB0::10::9::INSTR', 'GPIB0::10::INSTR', 'ASRL3::INSTR')`

I just use 'GPIB0::10::INSTR', Please let me know if you need anything else.

**Comment by MatthieuDartiailh** [comment]
Do we agree that when tested close you did something like the following ?
```python
import visa

if __name__ == '__main__':
    rm = visa.ResourceManager()
    gpibid='GPIB0::10::INSTR'
    instrument = rm.open_resource(gpibid)
    device_model = instrument.query("*IDN?")
    print(device_model)
    instrument.close()
```

I am asking because if you did, the code raising the error should never be reached since the attribute `session` of your object will raise when accessed and it is accessed when calling `disable_events`.

Your instrument seems to 'support' what is known as secondary GPIB addresses or at least does as if. You cannot do anything to remove those form the list of discovered instruments. By the way could you let me know what instrument you are trying to talk to ?
Also could you check (not related to your issue) that you get the same answer to `'*IDN?'` whether you use `GPIB0::10::INSTR` or `GPIB0::10::0::INSTR` ?

**Comment by sumanthraja** [comment]
As said above I am trying to do same as in the snippet, That's the initial step. From there I want to do multiple operations.

I am working on **TEMPTRONIC ATS-605(Thermo Stream)**. I used different 'GPIB0::10::x::INSTR'out of it I was able to use only two of them x = 2, 9; and for remaining of them I got this error as below

<img width="352" alt="double" src="https://user-images.githubusercontent.com/23439472/49123058-0a6b6400-f26c-11e8-8118-7ed48a02aa78.PNG">

**Comment by MatthieuDartiailh** [comment]
Closing for lack of activity (by my fault). I feel like the issue of the ResourceManager is not something truly specific to PyVISA but a problem of lifetime. Feel free to reopen if necessary.
