### ISSUE TITLE
read_to_file() not implement error

### ISSUE THREAD

**Issue by vanguoo** [pyvisa/pyvisa#465]
Hi,
I am just getting started with python and pyvisa
I am going to write the measurement data to file but i got an error with this function

here is the code:
from gpib_ctypes import make_default_gpib
make_default_gpib()
import visa
import pyvisa
rm = visa.ResourceManager('@py')
lib =rm.visalib
ket = rm.open_resource('GPIB0::24::INSTR')
#get started with sweep operation
lib.write(ket.session,b'*RST')
lib.write(ket.session,b':SENS:FUNC:CONC OFF')
lib.write(ket.session,b':SOUR:FUNC CURR')
lib.write(ket.session,b':SENS:FUNC "VOLT:DC"')
lib.write(ket.session,b':SENS:VOLT:PROT 10')
lib.write(ket.session,b':SOUR:CURR:START -1E-6')
lib.write(ket.session,b':SOUR:CURR:STOP 1E-6')
lib.write(ket.session,b':SOUR:CURR:STEP 1E-7')
lib.write(ket.session,b':SOUR:CURR:MODE SWE')
lib.write(ket.session,b':SOUR:SWE:RANG AUTO')
lib.write(ket.session,b':SOUR:SWE:SPAC LIN')
lib.write(ket.session,b':TRIG:COUN 30')
lib.write(ket.session,b':SOUR:DEL 0.1')
lib.write(ket.session,b':OUTP ON')
lib.write(ket.session,b':INIT')
lib.write(ket.session,b':TRACe:DATA?')
lib.read_to_file(ket.session,'data.txt',9999)

here is the error:
Traceback (most recent call last):
  File "C:/Program Files/Python36/Lib/site-packages/test.py", line 38, in <module>
    lib.read_to_file(ket.session,'data.txt',9999)
  File "C:\Program Files\Python36\Lib\site-packages\pyvisa\highlevel.py", line 1220, in read_to_file
    raise NotImplementedError
NotImplementedError

**Comment by Vanguo996** [comment]
according to the manual,
i can  not instantiate the write() method  as you guys 
why?

![image](https://user-images.githubusercontent.com/55241884/66995995-782db200-f102-11e9-9b32-e5e6b4e1b704.png)

Machine Details:
   Platform ID:    Windows-7-6.1.7601-SP1
   Processor:      Intel64 Family 6 Model 60 Stepping 3, GenuineIntel

Python:
   Implementation: CPython
   Executable:     c:\program files\python36\python.exe
   Version:        3.6.0
   Compiler:       MSC v.1900 64 bit (AMD64)
   Bits:           64bit
   Build:          Dec 23 2016 08:06:12 (#v3.6.0:41df79263a11)
   Unicode:        UCS4

PyVISA Version: 1.10.1

Backends:
   ni:
      Version: 1.10.1 (bundled with PyVISA)
      #1: C:\Windows\system32\visa32.dll:
         found by: auto
         bitness: 64
         Vendor: National Instruments
         Impl. Version: 19922944
         Spec. Version: 5244928
      #2: C:\Windows\system32\visa64.dll:
         found by: auto
         bitness: 64
         Vendor: National Instruments
         Impl. Version: 19922944
         Spec. Version: 5244928
   py:
      Version: 0.3.1
      ASRL INSTR: Available via PySerial (3.4)
      USB INSTR:
         PyUSB does not seem to be properly installed.
         Please refer to PyUSB documentation and
         install a suitable backend like
         libusb 0.1, libusb 1.0, libusbx,
         libusb-win32 or OpenUSB.
         No backend available
      USB RAW:
         PyUSB does not seem to be properly installed.
         Please refer to PyUSB documentation and
         install a suitable backend like
         libusb 0.1, libusb 1.0, libusbx,
         libusb-win32 or OpenUSB.
         No backend available
      TCPIP INSTR: Available
      TCPIP SOCKET: Available
      GPIB INSTR:
         Please install linux-gpib to use this resource type.
         No module named 'gpib'


i am really appreciate with your help!
:-)

**Comment by MatthieuDartiailh** [comment]
Since you are on Windows you really do not need to go through the pyvisa-py backend. The error you are seeing is because that function has not been implemented in that backend (in my experience it is rarely used), but should work on the default backend. If you want to contribute a PR to pyvisa-py to add it feel free to do so.

Regarding `write`, your autocompletion engine is confused by the fact that `open_resource` returns different classes depending on the address. It is definitively available on GPIB INSTR resources.
