### ISSUE TITLE
Timeout Error when write queries are sent.

### ISSUE THREAD

**Issue by nadeemass** [pyvisa/pyvisa#570]
Hi,

I am using the Pyvisa package to help me connect to an Oscilloscope (Tektronix DPO2012B), when i send read only quires no exceptions are thrown, whenever i start querying the oscilloscope sending write commands, Timeout error exception is thrown although the command succeeded, timeout, delay, read/write termination did not help me solve this problem.

The error i am getting continuously: 
Traceback (most recent call last):
  File "D:/Nadeem/Nyxoah/PyProjects/proj1/main.py", line 19, in <module>
    inst.query("CURSor:FUNCtion OFF")
  File "D:\Nadeem\Nyxoah\PyProjects\proj1\venv\lib\site-packages\pyvisa\resources\messagebased.py", line 644, in query
    return self.read()
  File "D:\Nadeem\Nyxoah\PyProjects\proj1\venv\lib\site-packages\pyvisa\resources\messagebased.py", line 486, in read
    message = self._read_raw().decode(enco)
  File "D:\Nadeem\Nyxoah\PyProjects\proj1\venv\lib\site-packages\pyvisa\resources\messagebased.py", line 442, in _read_raw
    chunk, status = self.visalib.read(self.session, size)
  File "D:\Nadeem\Nyxoah\PyProjects\proj1\venv\lib\site-packages\pyvisa\ctwrapper\functions.py", line 2337, in read
    ret = library.viRead(session, buffer, count, byref(return_count))
  File "D:\Nadeem\Nyxoah\PyProjects\proj1\venv\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 222, in _return_handler
    return self.handle_return_value(session, ret_value)  # type: ignore
  File "D:\Nadeem\Nyxoah\PyProjects\proj1\venv\lib\site-packages\pyvisa\highlevel.py", line 251, in handle_return_value
    raise errors.VisaIOError(rv)
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.

Any suggestions?
Thank you,

**Comment by MatthieuDartiailh** [comment]
Usually instruments do not answer to write commands. As a consequence there is nothing to read after writing (since query is just write then read) and the timeout is normal. Simply use write in that case.
