### ISSUE TITLE
[COM] Communication issue with Keithley 6514 Electrometer using KUSB-488B USB to GPIB Interface Adapter

### ISSUE THREAD

**Issue by gentle-giant** [pyvisa/pyvisa#599]
Instrument details
------------------
* Model: Keithley 6514 Electrometer (Firmware version: A11)
* Communication: GPIB via KUSB-488B USB to GPIB Interface Adapter
* Link to the documentation (if available): [6514_901_01.PDF](https://github.com/pyvisa/pyvisa/files/6458949/6514_901_01.PDF)

Output of `pyvisa-info`
-----------------------
```
Machine Details:
   Platform ID:    Windows-10-10.0.19041-SP0
   Processor:      Intel64 Family 6 Model 165 Stepping 3, GenuineIntel

Python:
   Implementation: CPython
   Executable:     c:\users\acullen\.virtualenvs\piezo-poker-ne2dep67\scripts\python.exe
   Version:        3.7.8
   Compiler:       MSC v.1916 64 bit (AMD64)
   Bits:           64bit
   Build:          Jun 28 2020 08:53:46 (#tags/v3.7.8:4b47a5b6ba)
   Unicode:        UCS4

PyVISA Version: 1.11.3

Backends:
   ivi:
      Version: 1.11.3 (bundled with PyVISA)
      #1: C:\Windows\system32\visa32.dll:
         found by: auto
         bitness: 64
         Vendor: National Instruments
         Impl. Version: National Instruments
         Spec. Version: National Instruments
      #2: C:\Windows\system32\visa64.dll:
         found by: auto
         bitness: 64
         Vendor: National Instruments
         Impl. Version: National Instruments
         Spec. Version: National Instruments
```
Problem Description
-----------------------
I'm developing a data acquisition system that makes use of your pyvisa library for communication with a Keithley 6514 Electrometer and I'm having communication stability issues. The system needs to sample the charge measurement function on the electrometer at a rate of 100 Hz for tests that run for several days. Everything seems to be working well except the communication to the electrometer is only stable for several hours after which the communications crashes reporting the error: 

```
2021-05-10 20:11:58,015 - pyvisa - DEBUG - viWrite(1, b':READ?;\r\n', 9, 'c_ulong(9)') -> 0
2021-05-10 20:11:58,123 - pyvisa - DEBUG - GPIB0::14::0::INSTR - reading 20480 bytes (last status <StatusCode.success_max_count_read: 1073676294>)
2021-05-10 20:11:58,129 - pyvisa - DEBUG - viRead(1, <ctypes.c_char_Array_20480 object at 0x00000207058D30C8>, 20480, 'c_ulong(42)') -> 0
2021-05-10 20:11:58,187 - pyvisa - DEBUG - viWrite(1, b':READ?;\r\n', 9, 'c_ulong(0)') -> -1073807342
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\tkinter\__init__.py", line 749, in callit
    func(*args)
  File "C:\Users\user\.virtualenvs\piezo-poker-Ne2DEP67\lib\site-packages\matplotlib\backends\_backend_tk.py", line 139, in _on_timer
    super()._on_timer()
    ret = func(*args, **kwargs)
  File "C:\Users\user\.virtualenvs\piezo-poker-Ne2DEP67\lib\site-packages\matplotlib\animation.py", line 1477, in _step
    still_going = super()._step(*args)
  File "C:\Users\user\.virtualenvs\piezo-poker-Ne2DEP67\lib\site-packages\matplotlib\animation.py", line 1188, in _step
    framedata = next(self.frame_seq)
  File "C:\Users\user\.virtualenvs\piezo-poker-Ne2DEP67\lib\site-packages\matplotlib\animation.py", line 1681, in iter_frames
    yield from this
  File "C:\Users\user\path\to\file\piezoMeasure.py", line 486, in getNewData
    data = self.electrometer.getNewReading()["read"][0]
  File "C:\Users\user\path\to\file\modules\keithley6514\keithley6514.py", line 604, in getNewReading      
    response = self.device.query(":READ?;")
    self.write(message)
  File "C:\Users\user\.virtualenvs\piezo-poker-Ne2DEP67\lib\site-packages\pyvisa\resources\messagebased.py", line 197, in write
    count = self.write_raw(message.encode(enco))
  File "C:\Users\user\.virtualenvs\piezo-poker-Ne2DEP67\lib\site-packages\pyvisa\resources\messagebased.py", line 157, in write_raw
    return self.visalib.write(self.session, message)[0]
  File "C:\Users\user\.virtualenvs\piezo-poker-Ne2DEP67\lib\site-packages\pyvisa\ctwrapper\functions.py", line 2796, in write
    ret = library.viWrite(session, data, len(data), byref(return_count))
    return self.handle_return_value(session, ret_value)  # type: ignore
  File "C:\Users\user\.virtualenvs\piezo-poker-Ne2DEP67\lib\site-packages\pyvisa\highlevel.py", line 251, in handle_return_value
    raise errors.VisaIOError(rv)
pyvisa.errors.VisaIOError: VI_ERROR_INV_RSRC_NAME (-1073807342): Invalid resource reference specified. Parsing error.
```

After this error the electrometer seems to be stuck in a listener state (LSTN front panel indicator is illuminated). Typically the electrometer needs to be power cycled and the GPIB-USB adapter unplugged to reestablish communication. 

So far I've tried:
1. Updating the electrometer to the most recent firmware version 
2. Testing communication with a supported DAQ software (Kickstart 2.5). Seems to be stable.
3. Setting the query_delay to 0.01 
4. Slowing the sample rate from 100Hz to 10Hz (electrometer is capable of up to 500 samples/second over the GPIB port)

No luck so far. Do you have any recommendations for how improve the communication stability? Or if this is unavoidable, how would you recommend going about recovering communication with the equipment after a crash.

**Comment by fonckv** [comment]
Hello @gentle-giant,

I have been having some serious issues to communicate with this tool using pyvisa. I was wondering if you'd share your code ? This would greatly help me.

Have a nice day
