### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf4 in position 723: ordinal not in range(128)

### ISSUE THREAD

**Issue by nejanthirakesh** [pyvisa/pyvisa#631]
### **Instrument details**
----------------------------------------------------
* Model: AWG 70002A Tektronix
* Communication: TCPIP
* Link to the documentation (if available): https://download.tek.com/manual/AWG70000A-Programmer-Manual-077078207.pdf
----------------------------------------------------
### **Output of pyvisa-info:**

Machine Details:
   Platform ID:    Windows-10-10.0.19042-SP0
   Processor:      Intel64 Family 6 Model 142 Stepping 9, GenuineIntel

Python:
   Implementation: CPython
   Executable:     C:\Users\xxxx\.conda\envs\minimodule_dev\python.exe
   Version:        3.9.7
   Compiler:       MSC v.1916 64 bit (AMD64)
   Bits:           64bit
   Build:          Sep 14 2021 01:11:01 (#default)
   Unicode:        UCS4

PyVISA Version: 1.11.3

Backends:
   ivi:
      Version: 1.11.3 (bundled with PyVISA)
      #1: C:\WINDOWS\system32\visa32.dll:
         found by: auto
         bitness: 64
         Vendor: Keysight Technologies
         Impl. Version: Keysight Technologies
         Spec. Version: Keysight Technologies
      #2: C:\WINDOWS\system32\visa64.dll:
         found by: auto
         bitness: 64
         Vendor: Keysight Technologies
         Impl. Version: Keysight Technologies
         Spec. Version: Keysight Technologies
   py:
      Version: 0.5.2
      ASRL INSTR:
         Please install PySerial (>=3.0) to use this resource type.
         No module named 'serial'
      USB INSTR: Available via PyUSB (1.2.1). Backend: libusb1
      USB RAW: Available via PyUSB (1.2.1). Backend: libusb1
      TCPIP INSTR: Available
      TCPIP SOCKET: Available
      GPIB INSTR:
         Please install linux-gpib (Linux) or gpib-ctypes (Windows, Linux) to use this resource type. Note that installing gpib-ctypes will give you access to a broader range of funcionality.
         No module named 'gpib'

-------------------------------------------------------------------------
**### Error:**
Traceback (most recent call last):
  File "C:\MyWorkspace\SourceTree\Repositories\measurement_scripts\scripts\Awg_Test_70012.py", line 83, in <module>
    awg.check_errors()
  File "C:\MyWorkspace\SourceTree\Repositories\rfinstruments\rfinstruments\instruments\awg70002a.py", line 135, in check_errors
    error = self.instr.query('system:error:all?')
  File "C:\Users\xxxx\.conda\envs\minimodule_dev\lib\site-packages\pyvisa\resources\messagebased.py", line 644, in query
    return self.read()
  File "C:\Users\xxxx\.conda\envs\minimodule_dev\lib\site-packages\pyvisa\resources\messagebased.py", line 486, in read
    message = self._read_raw().decode(enco)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf4 in position 723: ordinal not in range(128)

Process finished with exit code 1

-------------------------------------------------------------------------
Problem Description:
Hello,  
 I am controlling AWG 70002A to generate OFDM signal using python and pyVISA.
Generating OFDM_I and a Marker signal on channel 1 and OFDM_Q on channel 2.
1) OFDM_I generation (same for OFDM_Q): Code
wfm_header = 'wlist:waveform:data "{:s}", 0, {:d} ,'.format(name, chunk_size, len(str(wfm_bytes)), wfm_bytes)
wav_tr = self.instr.write_binary_values(wfm_header, waveform) .**...A**
_IO Monitor output in Keysight Connection expert:_
wlist:waveform:data "OFDM_Test_I", 0, 20480 ,#581920�... r...�..%sr..�,.�$..a,F�I�.<�.�<��.=��.=\nt.=..�<9e.<..6<./i<3k�<ۥu=(.�=�..>+:">...>?T�=���<.�p.$�..M'....*.9�......:...�.�.�.)..C....�..��.�.x."..��pq=$.�=.��=�.�=�?.=�.�.`{..�.�..��..j�.�\...%M.T�..
2) Marker Generation: Code
marker_header = 'wlist:waveform:marker:data "{:s}", 0, {:d}, '.format(name, length, len(str(marker_bytes)),
                                                                              marker_bytes)
mark_tr = self.instr.write_binary_values(marker_header, marker_array, datatype='B')  **...B**
_IO Monitor output in Keysight Connection expert:_
wlist:waveform:marker:data "OFDM_Test_I", 0, 20480, #520480@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

**Marker signal as mentioned in 2) is created as required on AWG and is working perfectly. But when it comes to OFDM signal generation, it throws UnicodeDecode error.**
- the variable **marker__array** in **...B** is a numpy array(20480, ) [64, 64, 64,.....0, 0, 0] of int8, whereas the variable **waveform** in **...A** is float 64 type which is a numpy array(20480, ) of float and real different numbers.
- However, when I tried enetering np.full(20428, 1 or -0.005 or any number here, i.e repetitive) in place of variable **waveform** in **...A**, the code transfers to AWG perfectly!!
- I tried enetring encoding= 'UTF-8', or 'latin1' in statement **...A** , nothing works.
- I tried adding another parameter datatype='B' in **...A** as I did for marker, but it throws struct.error: required argument is not an integer
- Using PyVisa message based Resource Class:
      write_binary_values{   
        message: str,
        values: Sequence[Any],
        datatype: util.BINARY_DATATYPES = "f",
        is_big_endian: bool = False,
        termination: Optional[str] = None,
        encoding: Optional[str] = None,
        header_fmt: util.BINARY_HEADERS = "ieee",}

_Note: The same code transfers with a warning onto AWG 70002A in the previous FW version: 6.1.0046.0 , but for the latest FW: 7.1.0170.0 , this error is occuring._

Could you please help in pointing out on why the error is occuring in write_binary_values in **...A** , also please let me know if I have not identified correctly the cause of the error?

Thank You.

**Comment by nejanthirakesh** [comment]
Thanks for your reply. I used read_raw and found out that certain characters were not decoded properly. This mismatch in encoding was only seen in AWG with FW Version:7.1 which had older version of TekVISA. Tektronix provided latest version of TekVISA and the issue was solved.
