### ISSUE TITLE
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed (Keysight E36313A)

### ISSUE THREAD

**Issue by Kuper101** [pyvisa/pyvisa#676]
While performing a query to my Keysight E36313A I receive a timeout error. Write command working fine, read command results in timeout error.
OS: Ubuntu 20.04
Connection type: USB
Device docs: 
[9018-04577.pdf](https://github.com/pyvisa/pyvisa/files/9039484/9018-04577.pdf)
pyvisa-info result:
Machine Details:
   Platform ID:    Linux-5.13.0-51-generic-x86_64-with-glibc2.31
   Processor:      x86_64

Python:
   Implementation: CPython
   Executable:     /home/arbe/gitlab/arbe_phoenixcontrol_automation/venv/bin/python3.9
   Version:        3.9.13
   Compiler:       GCC 9.4.0
   Bits:           64bit
   Build:          May 23 2022 22:01:06 (#main)
   Unicode:        UCS4

PyVISA Version: 1.12.0

Backends:
   ivi:
      Version: 1.12.0 (bundled with PyVISA)
      Binary library: Not found
   py:
      Version: 0.5.3
      ASRL INSTR: Available via PySerial (3.5)
      USB INSTR: Available via PyUSB (1.2.1). Backend: libusb1
      USB RAW: Available via PyUSB (1.2.1). Backend: libusb1
      TCPIP INSTR: Available 
      TCPIP SOCKET: Available 
      GPIB INSTR:
         Please install linux-gpib (Linux) or gpib-ctypes (Windows, Linux) to use this resource type. Note that installing gpib-ctypes will give you access to a broader range of funcionality.
         No module named 'gpib'

my code:
`import pyvisa
rm = pyvisa.pyvisa.ResourceManager()
rm.list_resources()`
#('ASRL/dev/ttyS0::INSTR',)
inst = rm.open_resource('ASRL/dev/ttyS0::INSTR')
inst.write('*IDN?')
#7
inst.read()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/arbe/gitlab/arbe_phoenixcontrol_automation/venv/lib/python3.9/site-packages/pyvisa/resources/messagebased.py", line 486, in read
    message = self._read_raw().decode(enco)
  File "/home/arbe/gitlab/arbe_phoenixcontrol_automation/venv/lib/python3.9/site-packages/pyvisa/resources/messagebased.py", line 442, in _read_raw
    chunk, status = self.visalib.read(self.session, size)
  File "/home/arbe/gitlab/arbe_phoenixcontrol_automation/venv/lib/python3.9/site-packages/pyvisa_py/highlevel.py", line 519, in read
    return data, self.handle_return_value(session, status_code)
  File "/home/arbe/gitlab/arbe_phoenixcontrol_automation/venv/lib/python3.9/site-packages/pyvisa/highlevel.py", line 251, in handle_return_value
    raise errors.VisaIOError(rv)
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.

**Comment by MatthieuDartiailh** [comment]
First you need to configure the write and read termination character as follow (the manual specify that a feedline is used):
```python
inst = rm.open_resource('ASRL/dev/ttyS0::INSTR', write_termination="\n", read_termination="\n")
```
Furthermore, since your connection is through an emulated serial port you may have to configure the baud rate and other serial specific parameters but those are not listed in the attached manual.
