### ISSUE TITLE
pyvisa is not thread safe

### ISSUE THREAD

**Issue by mawenzy** [pyvisa/pyvisa#726]
In your docs, you state that pyvisa is [thread safe](https://pyvisa.readthedocs.io/en/latest/faq/faq.html#is-pyvisa-thread-safe). From my experience, this does not seem to be the case. For example, the following code using a Keysight dmm breaks.

To Reproduce
--------------
```py
import threading
import time
import pyvisa

rm = pyvisa.ResourceManager()
inst = rm.open_resource('TCPIP0::192.168.1.109::INSTR')
inst.write_termination = "\n"
inst.read_termination = "\n"
inst.timeout = 10000

def _run():
    while True:
        inst.query("*OPC?")

for _ in range(2):
    thread = threading.Thread(target= _run, daemon=True)
    thread.start()

while True:
    time.sleep(1)
```
Error message:

```py
Exception in thread Thread-2 (_run):
Traceback (most recent call last):
  File "C:\Users\BlueFors\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\BlueFors\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\BlueFors\Documents\p5control-bluefors\test_display.py", line 13, in _run
    inst.query("*OPC?")
  File "C:\Users\BlueFors\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyvisa\resources\messagebased.py", line 648, in query
    return self.read()
           ^^^^^^^^^^^
  File "C:\Users\BlueFors\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyvisa\resources\messagebased.py", line 486, in read
    message = self._read_raw().decode(enco)
              ^^^^^^^^^^^^^^^^
  File "C:\Users\BlueFors\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyvisa\resources\messagebased.py", line 442, in _read_raw
    chunk, status = self.visalib.read(self.session, size)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BlueFors\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyvisa\ctwrapper\functions.py", line 2337, in read
    ret = library.viRead(session, buffer, count, byref(return_count))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BlueFors\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 226, in _return_handler
    return self.handle_return_value(session, ret_value)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BlueFors\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyvisa\highlevel.py", line 251, in handle_return_value
    raise errors.VisaIOError(rv)
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.
```

**Output of `pyvisa-info`**
```


Machine Details:
   Platform ID:    Windows-10-10.0.22621-SP0
   Processor:      Intel64 Family 6 Model 165 Stepping 5, GenuineIntel

Python:
   Implementation: CPython
   Executable:     C:\Users\BlueFors\AppData\Local\Programs\Python\Python311\python.exe
   Version:        3.11.0
   Compiler:       MSC v.1933 64 bit (AMD64)
   Bits:           64bit
   Build:          Oct 24 2022 18:26:48 (#main)
   Unicode:        UCS4

PyVISA Version: 1.13.0

Backends:
   ivi:
      Version: 1.13.0 (bundled with PyVISA)
      #1: C:\WINDOWS\system32\visa32.dll:
         found by: auto
         bitness: 64
         Vendor: National Instruments
         Impl. Version: 23069952
         Spec. Version: 5244928
      #2: C:\WINDOWS\system32\visa64.dll:
         found by: auto
         bitness: 64
         Vendor: National Instruments
         Impl. Version: 23069952
         Spec. Version: 5244928
   py:
      Version: 0.5.3
      ASRL INSTR:
         Please install PySerial (>=3.0) to use this resource type.
         No module named 'serial'
      USB INSTR:
         Please install PyUSB to use this resource type.
         No module named 'usb'
      USB RAW:
         Please install PyUSB to use this resource type.
         No module named 'usb'
      TCPIP INSTR: Available
      TCPIP SOCKET: Available
      GPIB INSTR:
         Please install linux-gpib (Linux) or gpib-ctypes (Windows, Linux) to use this resource type. Note that installing gpib-ctypes will give you access to a broader range of funcionality.
         No module named 'gpib'
```

If I include my own lock, the example will not produce any error. Therefore, I conclude that pyvisa is not thread safe. As an example, the function:

https://github.com/pyvisa/pyvisa/blob/67744e5f0ebd4eb2e42ee91d2ba021eb6db9c48c/pyvisa/resources/messagebased.py#L625

is not thread safe, since it is not assured that after the ``write``, the ``read`` is executed before any other thread might write something different to the device, see also [this](https://github.com/pyvisa/pyvisa-py/issues/220#issuecomment-594718620) issue. If I am not mistaken, I would suggest that you clarify in your docs that pyvisa is not thread safe.

**Comment by MatthieuDartiailh** [comment]
The wording of the documentation lacks clarity I agree however what you describe is not a thread safety issue in PyVISA but a more generic problem that some resources require some communication patterns that cannot be enforced at the library level.

Let me explain. PyVISA is thread safe in that performing multiple operation from different threads will not lead to a corrupt state of PyVISA (as long as the backend is threadsafe, which is probably not completely true for pyvisa-py) and will not create an inconsistent state on the resources (no invalid attribute state, or mangled messages). However if a resource requires a specific ordering of operations to work properly we cannot enforce it meaningfully at the level of PyVISA since people will always be free to use write and read separately and hence locking around query would bring only a very minimal benefit.

So we should definitively clarify the documentation and if you want to take a stab at it you are very welcome.
