### ISSUE TITLE
[COM] Communication issue with IT6722 using USB

### ISSUE THREAD

**Issue by taigeer-maker** [pyvisa/pyvisa#731]
Instrument details
------------------
* Model:IT6722
* Communication: USB
* Link to the documentation (if available):
from pyvisa import ResourceManager
rm = ResourceManager()
inst = rm.open_resource(resource_name="USB0::0xFFFF::0x6700::602260010717710008::0::INSTR")
Output of `pyvisa-info`
-----------------------

Traceback (most recent call last):
  File "d:\test.py", line 3, in <module>
    inst = rm.open_resource(resource_name="USB0::0xFFFF::0x6700::602260010717710008::0::INSTR")
  File "C:\Users\realsil\AppData\Roaming\Python\Python39\site-packages\pyvisa\highlevel.py", line 3304, in open_resource
    res.open(access_mode, open_timeout)
  File "C:\Users\realsil\AppData\Roaming\Python\Python39\site-packages\pyvisa\resources\resource.py", line 297, in open
    self.session, status = self._resource_manager.open_bare_resource(
  File "C:\Users\realsil\AppData\Roaming\Python\Python39\site-packages\pyvisa\highlevel.py", line 3232, in open_bare_resource
    return self.visalib.open(self.session, resource_name, access_mode, open_timeout)
  File "C:\Users\realsil\AppData\Roaming\Python\Python39\site-packages\pyvisa\ctwrapper\functions.py", line 1851, in open
    ret = library.viOpen(
  File "C:\Users\realsil\AppData\Roaming\Python\Python39\site-packages\pyvisa\ctwrapper\highlevel.py", line 222, in _return_handler
    return self.handle_return_value(session, ret_value)  # type: ignore
  File "C:\Users\realsil\AppData\Roaming\Python\Python39\site-packages\pyvisa\highlevel.py", line 251, in handle_return_value
    raise errors.VisaIOError(rv)
pyvisa.errors.VisaIOError: VI_ERROR_IO (-1073807298): Could not perform operation because of I/O error.

**Comment by MatthieuDartiailh** [comment]
Can you access the resource using Keysight connection Expert ? 

Could you share the manual (feel free to send it by email) ? I cannot access it on ITech website.
