### ISSUE TITLE
Error Library cant be found

### ISSUE THREAD

**Issue by charinano** [pyvisa/pyvisa#765]
hi,
Last week I was using communicating just fine with my electronic load, but since yesterday, this error keeps coming up:

Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 162, in _init
    lib = Library(self.library_path)
  File "C:\Python311\Lib\ctypes\__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Program Files (x86)\IVI Foundation\VISA' (or one of its dependencies). Try using the full path with constructor syntax.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#11>", line 1, in <module>
    rm=pyvisa.ResourceManager()
  File "C:\Python311\Lib\site-packages\pyvisa\highlevel.py", line 2992, in __new__
    visa_library = open_visa_library(visa_library)
  File "C:\Python311\Lib\site-packages\pyvisa\highlevel.py", line 2904, in open_visa_library
    return cls(argument)
  File "C:\Python311\Lib\site-packages\pyvisa\highlevel.py", line 191, in __new__
    obj._init()
  File "C:\Python311\Lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 164, in _init
    raise errors.LibraryError.from_exception(exc, self.library_path)
pyvisa.errors.LibraryError: Error while accessing C:\Program Files (x86)\IVI Foundation\VISA: Could not find module 'C:\Program Files (x86)\IVI Foundation\VISA' (or one of its dependencies). Try using the full path with constructor syntax.

The only previous code lines were: 
```
import pyvisa 
rm=pyvisa.ResourceManager()

```

I have tried adding the path directory in different ways:
rm=pyvisa.ResourceManager('C:\Python311\Lib\site-packages\pyvisa')
rm=pyvisa.ResourceManager('C:\Program Files (x86)\IVI Foundation\VISA')
rm=pyvisa.ResourceManager('C:\WINDOWS\system32\visa32.dll') 
etc.
I have deinstalled and re-installed everything related in my compiter from the Ni_Visa library to the pyvisa packages to python itself, deleted all the fast and tried again but the error keeps coming up. 

When I write:
```
import pyvisa
rm=pyvisa.ResourceManager('@py')
print(rm.list_resources())
```
It returns an empty value ().
And I dont know what else to try. 

I'd greatly appreciate any prod in the right direction!
Cheers

Instrument details
------------------
* Model: Rigol DL3000
* Communication: USB
* Link to the documentation (if available):

Output of `pyvisa-info`
-----------------------
C:\Users\chari>pyvisa-info
Machine Details:
 
   Processor:      Intel64 Family 6 Model 126 Stepping 5, GenuineIntel

Python:
   Implementation: CPython
   Executable:     C:\Python311\python.exe
   Version:        3.11.4
   Compiler:       MSC v.1934 64 bit (AMD64)
   Bits:           64bit
   Build:          Jun  7 2023 05:45:37 (#tags/v3.11.4:d2340ef)
   Unicode:        UCS4

PyVISA Version: 1.13.0

Backends:
   ivi:
      Version: 1.13.0 (bundled with PyVISA)
      #1: C:\WINDOWS\system32\visa32.dll:
         found by: auto
         bitness: 64
         Vendor: National Instruments
         Impl. Version: 24118528
         Spec. Version: 7340032
      #2: C:\WINDOWS\system32\visa64.dll:
         found by: auto
         bitness: 64
         Vendor: National Instruments
         Impl. Version: 24118528
         Spec. Version: 7340032
   py:
      Version: 0.7.0
      TCPIP INSTR: Available
         Resource discovery:
         - VXI-11: ok
         - hislip: ok
      TCPIP SOCKET: Available
      ASRL INSTR:
         Please install PySerial (>=3.0) to use this resource type.
         No module named 'serial'
      USB INSTR:
         Please install PyUSB to use this resource type.
         No module named 'usb'
      USB RAW:
         Please install PyUSB to use this resource type.
         No module named 'usb'
      VICP INSTR:
         Please install PyVICP to use this resource type.
      GPIB INSTR:
         Please install linux-gpib (Linux) or gpib-ctypes (Windows, Linux) to use this resource type. Note that installing gpib-ctypes will give you access to a broader range of functionalities.
         No module named 'gpib'
      GPIB INTFC:
         Please install linux-gpib (Linux) or gpib-ctypes (Windows, Linux) to use this resource type. Note that installing gpib-ctypes will give you access to a broader range of functionalities.
         No module named 'gpib'

**Comment by MatthieuDartiailh** [comment]
One thing you can try is to use `os.add_dll_directory` in case there is some sort of permission issue.

After, because somebody reported a weird behavior on 3.11.4,  could you try to downgrade to Python 3.11.3 and see if things work ?
