### ISSUE TITLE
[COM] Communication issue with Keysight82357B using pyvisa

### ISSUE THREAD

**Issue by lcontami** [pyvisa/pyvisa#778]
Instrument details
------------------
* Model: Keysight82357B 
* Communication: usb-to-GPIB converter
* [Link to the documentation](https://www.keysight.com/us/en/assets/9018-06141/quick-start-guides/9018-06141.pdf) 

Output of `pyvisa-info`
-----------------------
```
Machine Details:
   Platform ID:    Windows-10-10.0.22621-SP0
   Processor:      Intel64 Family 6 Model 186 Stepping 3, GenuineIntel

Python:
   Implementation: CPython
   Executable:     C:\Users\LaurianeContamin\anaconda3\envs\palmsens\python.exe
   Version:        3.8.18
   Compiler:       MSC v.1916 64 bit (AMD64)
   Bits:           64bit
   Build:          Sep 11 2023 13:39:12 (#default)
   Unicode:        UCS4

PyVISA Version: 1.11.0

Backends:
   ivi:
      Version: 1.11.0 (bundled with PyVISA)
      #1: C:\WINDOWS\system32\visa32.dll:
         found by: auto
         bitness: 64
         Vendor: National Instruments
         Impl. Version: National Instruments
         Spec. Version: National Instruments
      #2: C:\WINDOWS\system32\visa64.dll:
         found by: auto
         bitness: 64
         Vendor: National Instruments
         Impl. Version: National Instruments
         Spec. Version: National Instruments

```

I am using a usb to GPIB converter from Keysight to communicate with an instrument.
I installed the Keysight program suite and am able to detect and communicate with said instrument on Keysight IO.

I then installed pyvisa, but I am not able to detect it in the resource list.

I was wondering if it was an issue of visa backend since I had NI-Visa installed previously.
However I did not manage to force pyvisa to use my Keysight visa.

Here is what I tried:
```python
>>> import pyvisa
>>> rm = pyvisa.ResourceManager()
>>> rm
<ResourceManager(<IVIVisaLibrary('C:\\WINDOWS\\system32\\visa32.dll')>)>
# trying to point toward keysight DLL
>>> import os
>>> os.add_dll_directory(r"C:\Program Files\Keysight\IO Libraries Suite\bin")
<AddedDllDirectory('C:\\Program Files\\Keysight\\IO Libraries Suite\\bin')>
>>> os.add_dll_directory(r"C:\Program Files\Keysight\IO Libraries Suite")
<AddedDllDirectory('C:\\Program Files\\Keysight\\IO Libraries Suite')>
>>> rm = pyvisa.ResourceManager()
>>> rm
<ResourceManager(<IVIVisaLibrary('C:\\WINDOWS\\system32\\visa32.dll')>)>  # still the same path
# tring by giving the path
>>> path_to_visa = "C:\Program Files\Keysight\IO Libraries Suite\Keysight.Visa.dll"
>>> rm = pyvisa.ResourceManager(path_to_visa)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\LaurianeContamin\anaconda3\envs\palmsens\lib\site-packages\pyvisa\highlevel.py", line 3005, in __new__
    visa_library = open_visa_library(visa_library)
  File "C:\Users\LaurianeContamin\anaconda3\envs\palmsens\lib\site-packages\pyvisa\highlevel.py", line 2919, in open_visa_library
    return cls(argument)
  File "C:\Users\LaurianeContamin\anaconda3\envs\palmsens\lib\site-packages\pyvisa\highlevel.py", line 189, in __new__
    obj._init()
  File "C:\Users\LaurianeContamin\anaconda3\envs\palmsens\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 168, in _init
    functions.set_signatures(self.lib, errcheck=self._return_handler)
  File "C:\Users\LaurianeContamin\anaconda3\envs\palmsens\lib\site-packages\pyvisa\ctwrapper\functions.py", line 324, in set_signatures
    apply(
  File "C:\Users\LaurianeContamin\anaconda3\envs\palmsens\lib\site-packages\pyvisa\ctwrapper\functions.py", line 226, in _internal
    set_signature(library, function_name, argtypes, restype, errcheck_)
  File "C:\Users\LaurianeContamin\anaconda3\envs\palmsens\lib\site-packages\pyvisa\ctwrapper\functions.py", line 418, in set_signature
    func = getattr(library, function_name)
  File "C:\Users\LaurianeContamin\anaconda3\envs\palmsens\lib\ctypes\__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\LaurianeContamin\anaconda3\envs\palmsens\lib\ctypes\__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'viOpen' not found
```

Looking at the error in a previous issue I could only find a reference mentioning issues with 32bit python but this is not my case.
I do not understand why adding the Keysight dir did not help pointing toward the correct DLL.

Thanks in advance !

**Comment by lcontami** [comment]
After disabling Ni-VISA pyvisa could still not find Keysight; I got 

```
PyVISA Version: 1.11.0

Backends:
   ivi:
      Version: 1.11.0 (bundled with PyVISA)
      #1: C:\WINDOWS\system32\visa32.dll:
         found by: auto
         bitness: 64
         Could not get more info:
            VI_ERROR_LIBRARY_NFOUND (-1073807202): A code library required by VISA could not be located or loaded.
      #2: C:\WINDOWS\system32\visa64.dll:
         found by: auto
         bitness: 64
         Could not get more info:
            VI_ERROR_LIBRARY_NFOUND (-1073807202): A code library required by VISA could not be located or loaded.
```

I am uninstalling / reinstalling keysight.
