### ISSUE TITLE
[COM] Communication issue with R&S ESPI using RSIB Passport

### ISSUE THREAD

**Issue by fsmoewe** [pyvisa/pyvisa#798]
Hello,
I hope you can help me! Thank you in advance for your great work!

I'm currently trying to address an Rode&Schwarz ESPI3 over here with pyvisa. 
This uses the **RSIB** protocol.
I have NI VISA and the corresponding RSIB passport installed.

With NI's tool "Visa Interactive Control" i can reach and address the device under the resource "RSIB::169.254.168.15::INSTR". 

IDN? returns a valid response with "Rohde&Schwarz,ESPI-3,100331/003,2.92"
I also attached a screenshot of this NI-I/O Trace.

When try to do the same thing in Python with following:
`visa.log_to_screen()`
`rm = visa.ResourceManager()`
`inst = rm.open_resource('RSIB::169.254.168.15::INSTR')`
`inst.query('*IDN?')`

i get following errors:

> `2024-01-23 15:31:06,692 - pyvisa - DEBUG - No visa library specified, trying to find alternatives.
> 2024-01-23 15:31:06,693 - pyvisa - DEBUG - Environment variable PYVISA_LIBRARY is unset.
> 2024-01-23 15:31:06,703 - pyvisa - DEBUG - No user defined configuration
> 2024-01-23 15:31:06,705 - pyvisa - DEBUG - Automatically found library files: [None, 'C:\\Windows\\System32\\visa32.dll', 'C:\\Windows\\System32\\visa32.dll', 'C:\\Windows\\System32\\visa64.dll', 'C:\\Windows\\System32\\visa64.dll']
> 2024-01-23 15:31:06,706 - pyvisa - DEBUG - No user defined library files
> 2024-01-23 15:31:06,707 - pyvisa - DEBUG - The IVI implementation available
> 2024-01-23 15:31:06,707 - pyvisa - DEBUG - No user defined configuration
> 2024-01-23 15:31:06,710 - pyvisa - DEBUG - Automatically found library files: [None, 'C:\\Windows\\System32\\visa32.dll', 'C:\\Windows\\System32\\visa32.dll', 'C:\\Windows\\System32\\visa64.dll', 'C:\\Windows\\System32\\visa64.dll']
> 2024-01-23 15:31:06,711 - pyvisa - DEBUG - No user defined library files
> 2024-01-23 15:31:06,725 - pyvisa - DEBUG - Library signatures: 90 ok, 0 failed
> 2024-01-23 15:31:06,726 - pyvisa - DEBUG - Created library wrapper for C:\Windows\System32\visa32.dll
> 2024-01-23 15:31:06,953 - pyvisa - DEBUG - viOpenDefaultRM('<ViObject object at 0x00000290BB3C15D0>',) -> 0
> 2024-01-23 15:31:06,954 - pyvisa - DEBUG - Created ResourceManager with session 4097
> 2024-01-23 15:31:07,000 - pyvisa - DEBUG - viParseRsrcEx(4097, 'RSIB::169.254.168.15::INSTR', 'c_ushort(0)', 'c_ushort(0)', <ctypes.c_char_Array_256 object at 0x00000290BB3C3650>, <ctypes.c_char_Array_256 object at 0x00000290BB3C36D0>, <ctypes.c_char_Array_256 object at 0x00000290BB3C3750>) -> -1073807343
> Traceback (most recent call last):
>   File "c:\Users\some_home_path\script.py", line 5, in <module>
>     inst = rm.open_resource('RSIB::169.254.168.15::INSTR')
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\pyvisa\highlevel.py", line 3255, in open_resource
>     info = self.resource_info(resource_name, extended=True)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\pyvisa\highlevel.py", line 3182, in resource_info
>     ret, err = self.visalib.parse_resource_extended(self.session, resource_name)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\pyvisa\ctwrapper\functions.py", line 2076, in parse_resource_extended
>     ret = library.viParseRsrcEx(
>           ^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 226, in _return_handler
>     return self.handle_return_value(session, ret_value)  # type: ignore
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\pyvisa\highlevel.py", line 251, in handle_return_value
>     raise errors.VisaIOError(rv)
> pyvisa.errors.VisaIOError: VI_ERROR_RSRC_NFOUND (-1073807343): Insufficient location information or the requested device or resource is not present in the system.
> 2024-01-23 15:31:07,024 - pyvisa - DEBUG - Closing ResourceManager (session: 4097)
> 2024-01-23 15:31:07,088 - pyvisa - DEBUG - viClose(4097,) -> 0

i also attached a screenshot NI-I/O Trace  screenshot of that one
Maybe its something correlated/similar to #168, though i already tried with open_bare_resource

Instrument details
------------------
* Model: Rode&Schwarz ESPI3
* Communication: RSIB
* Link to the documentation (if available): https://www.rohde-schwarz.com/us/applications/remote-control-of-r-s-spectrum-and-network-analyzers-via-lan-application-note_56280-15634.html?change_c=true

Output of `pyvisa-info`
-----------------------
Machine Details:
   Platform ID:    Windows-10-10.0.19045-SP0
   Processor:      Intel64 Family 6 Model 186 Stepping 2, GenuineIntel

Python:
   Implementation: CPython
   Executable:     C:\WPy64-31140\python-3.11.4.amd64\python.exe
   Version:        3.11.4
   Compiler:       MSC v.1934 64 bit (AMD64)
   Architecture:   AMD64
   Build:          Jun  7 2023 05:45:37 (#tags/v3.11.4:d2340ef)
   Unicode:        UCS4

PyVISA Version: 1.14.1

Backends:
   ivi:
      Version: 1.14.1 (bundled with PyVISA)
      #1: C:\Windows\System32\visa32.dll:
         found by: auto
         architecture:
            ('x86', 64)
         Vendor: National Instruments
         Impl. Version: 24118528
         Spec. Version: 7340032
      #2: C:\Windows\System32\visa64.dll:
         found by: auto
         architecture:
            ('x86', 64)
         Vendor: National Instruments
         Impl. Version: 24118528
         Spec. Version: 7340032

NI-I/O Trace interactive control:
![image](https://github.com/pyvisa/pyvisa/assets/157499945/3e288016-a393-4aac-a9ce-04f33808565a)
NI-I/O Trace pyvisa:
![image](https://github.com/pyvisa/pyvisa/assets/157499945/33439308-72fe-4ca1-bf5c-43885a1cff50)

**Comment by MatthieuDartiailh** [comment]
PyVISA only call viParseRsrcEx if you do not specify a resource class. In your case you should be able to pass MessageBasedResource.

The next step would be to have proper support inside PyVISA with a dedicated resource class and proper resource name parsing.

**Comment by fsmoewe** [comment]
> PyVISA only call viParseRsrcEx if you do not specify a resource class. In your case you should be able to pass MessageBasedResource.
> 
> The next step would be to have proper support inside PyVISA with a dedicated resource class and proper resource name parsing.

Thank you for your answer!
Sadly it does not work yet. What do you need from me to investigate further?
Code:
`import pyvisa as visa`
`from pyvisa.resources import MessageBasedResource`
`visa.log_to_screen()`
`rm = visa.ResourceManager()`
`inst = rm.open_resource('RSIB::169.254.168.15::INSTR',resource_pyclass=MessageBasedResource)`
`print(inst.query('*IDN?'))`

results in:

> 2024-01-23 16:30:06,387 - pyvisa - DEBUG - No visa library specified, trying to find alternatives.
2024-01-23 16:30:06,387 - pyvisa - DEBUG - Environment variable PYVISA_LIBRARY is unset.
2024-01-23 16:30:06,400 - pyvisa - DEBUG - No user defined configuration
2024-01-23 16:30:06,402 - pyvisa - DEBUG - Automatically found library files: [None, 'C:\\Windows\\System32\\visa32.dll', 'C:\\Windows\\System32\\visa32.dll', 'C:\\Windows\\System32\\visa64.dll', 'C:\\Windows\\System32\\visa64.dll']
2024-01-23 16:30:06,402 - pyvisa - DEBUG - No user defined library files
2024-01-23 16:30:06,402 - pyvisa - DEBUG - The IVI implementation available
2024-01-23 16:30:06,403 - pyvisa - DEBUG - No user defined configuration
2024-01-23 16:30:06,404 - pyvisa - DEBUG - Automatically found library files: [None, 'C:\\Windows\\System32\\visa32.dll', 'C:\\Windows\\System32\\visa32.dll', 'C:\\Windows\\System32\\visa64.dll', 'C:\\Windows\\System32\\visa64.dll']
2024-01-23 16:30:06,405 - pyvisa - DEBUG - No user defined library files
2024-01-23 16:30:06,418 - pyvisa - DEBUG - Library signatures: 90 ok, 0 failed
2024-01-23 16:30:06,418 - pyvisa - DEBUG - Created library wrapper for C:\Windows\System32\visa32.dll
2024-01-23 16:30:06,664 - pyvisa - DEBUG - viOpenDefaultRM('<ViObject object at 0x000001517FE95550>',) -> 0
2024-01-23 16:30:06,664 - pyvisa - DEBUG - Created ResourceManager with session 4097
2024-01-23 16:30:06,665 - pyvisa - DEBUG - RSIB::169.254.168.15::INSTR - opening ...
2024-01-23 16:30:06,721 - pyvisa - DEBUG - viOpen(4097, 'RSIB::169.254.168.15::INSTR', <AccessModes.no_lock: 0>, 0, '<ViObject object at 0x000001517FE97550>') -> -1073807343
Traceback (most recent call last):
  File "c:\some_home_path\script.py", line 8, in <module>
    inst = rm.open_resource('RSIB::169.254.168.15::INSTR',resource_pyclass=MessageBasedResource)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\pyvisa\highlevel.py", line 3292, in open_resource
    res.open(access_mode, open_timeout)
  File "C:\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\pyvisa\resources\resource.py", line 281, in open
    self.session, status = self._resource_manager.open_bare_resource(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\pyvisa\highlevel.py", line 3217, in open_bare_resource
    return self.visalib.open(self.session, resource_name, access_mode, open_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\pyvisa\ctwrapper\functions.py", line 1850, in open
    ret = library.viOpen(
          ^^^^^^^^^^^^^^^
  File "C:\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 226, in _return_handler
    return self.handle_return_value(session, ret_value)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\pyvisa\highlevel.py", line 251, in handle_return_value
    raise errors.VisaIOError(rv)
pyvisa.errors.VisaIOError: VI_ERROR_RSRC_NFOUND (-1073807343): Insufficient location information or the requested device or resource is not present in the system.
2024-01-23 16:30:06,745 - pyvisa - DEBUG - Closing ResourceManager (session: 4097)
2024-01-23 16:30:06,811 - pyvisa - DEBUG - viClose(4097,) -> 0

![image](https://github.com/pyvisa/pyvisa/assets/157499945/dbeeb702-a735-40ec-84c9-038d006b5695)

**Comment by fsmoewe** [comment]
> First you can check that you can still access the device using NI (in case the instrument into some weird error mode).
Thank you! That's what i am always doing after each try! The instrument happily answers in NI Interactive Control

**Comment by MatthieuDartiailh** [comment]
Not sure if this will help but can you try the following to see if the VISA library can deal with the resource name.
```python
import pyvisa as visa
visa.log_to_screen()
rm = visa.ResourceManager()
print(rm.resource_info('RSIB::169.254.168.15::INSTR', extended=False)
```

**Comment by fsmoewe** [comment]
> Not sure if this will help but can you try the following to see if the VISA library can deal with the resource name.
> 
> ```python
> import pyvisa as visa
> visa.log_to_screen()
> rm = visa.ResourceManager()
> print(rm.resource_info('RSIB::169.254.168.15::INSTR', extended=False)
> ```

Thank you for trying! I appended the output of your script.

> 2024-01-24 09:46:36,907 - pyvisa - DEBUG - No visa library specified, trying to find alternatives.
2024-01-24 09:46:36,908 - pyvisa - DEBUG - Environment variable PYVISA_LIBRARY is unset.
2024-01-24 09:46:36,920 - pyvisa - DEBUG - No user defined configuration
2024-01-24 09:46:36,922 - pyvisa - DEBUG - Automatically found library files: [None, 'C:\\Windows\\System32\\visa32.dll', 'C:\\Windows\\System32\\visa32.dll', 'C:\\Windows\\System32\\visa64.dll', 'C:\\Windows\\System32\\visa64.dll']
2024-01-24 09:46:36,922 - pyvisa - DEBUG - No user defined library files
2024-01-24 09:46:36,923 - pyvisa - DEBUG - The IVI implementation available
2024-01-24 09:46:36,923 - pyvisa - DEBUG - No user defined configuration
2024-01-24 09:46:36,924 - pyvisa - DEBUG - Automatically found library files: [None, 'C:\\Windows\\System32\\visa32.dll', 'C:\\Windows\\System32\\visa32.dll', 'C:\\Windows\\System32\\visa64.dll', 'C:\\Windows\\System32\\visa64.dll']
2024-01-24 09:46:36,925 - pyvisa - DEBUG - No user defined library files
2024-01-24 09:46:36,940 - pyvisa - DEBUG - Library signatures: 90 ok, 0 failed
2024-01-24 09:46:36,941 - pyvisa - DEBUG - Created library wrapper for C:\Windows\System32\visa32.dll
2024-01-24 09:46:37,071 - pyvisa - DEBUG - viOpenDefaultRM('<ViObject object at 0x000001E02C385550>',) -> 0
2024-01-24 09:46:37,071 - pyvisa - DEBUG - Created ResourceManager with session 4097
2024-01-24 09:46:37,072 - pyvisa - DEBUG - viParseRsrc(4097, 'RSIB::169.254.168.15::INSTR', 'c_ushort(0)', 'c_ushort(0)') -> -1073807343
Traceback (most recent call last):
  File "c:\Users\some_path\some_script.py", line 4, in <module>
    print(rm.resource_info('RSIB::169.254.168.15::INSTR', extended=False))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\pyvisa\highlevel.py", line 3184, in resource_info
    ret, err = self.visalib.parse_resource(self.session, resource_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\pyvisa\ctwrapper\functions.py", line 2030, in parse_resource
    ret = library.viParseRsrc(
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 226, in _return_handler
    return self.handle_return_value(session, ret_value)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\pyvisa\highlevel.py", line 251, in handle_return_value
    raise errors.VisaIOError(rv)
pyvisa.errors.VisaIOError: VI_ERROR_RSRC_NFOUND (-1073807343): Insufficient location information or the requested device or resource is not present in the system.
2024-01-24 09:46:37,088 - pyvisa - DEBUG - Closing ResourceManager (session: 4097)
2024-01-24 09:46:37,092 - pyvisa - DEBUG - viClose(4097,) -> 0

**Comment by fsmoewe** [comment]
I'm just beginning to think that it could be due to the bitness? My backend is 64, my Python is 64, the Passport is 32(not available in 64 at all).
But if it's that, why can NI's "Visa Interactive Control" happily talk to the device?

Here is the trace of a successful ViOpen by NI's "Visa Interactive Control" and an unsuccessful ViOpen by pyVisa.
Do you see how the length of "&vi" differs from 64/32?

I know absolutely nothing about this, I just noticed it. I don't want to send anyone down the wrong track:
![image](https://github.com/pyvisa/pyvisa/assets/157499945/e77c7169-7103-4489-b492-1168559e5ae5)

**Comment by MatthieuDartiailh** [comment]
That's an interesting observation. If the passport has no 64 bits version then it will not be loaded by the 64 bits VISA lib. You can try installing a 32-bit python to see if it helps.

**Comment by fsmoewe** [comment]
okay so i grabed a portable 32Bit Python and installed pyvisa in there. The backend now looks like this:

>       Version: 1.14.1 (bundled with PyVISA)
>       #1: C:\Windows\System32\visa32.dll:
>          found by: auto
>          architecture:
>             ('x86', 32)
>          Vendor: National Instruments
>          Impl. Version: 24118528
>          Spec. Version: 7340032

my python is now:
> Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:20:04) [MSC v.1929 32 bit (Intel)] on win32

and i can talk to the device as a bare_resource!!!

```
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:20:04) [MSC v.1929 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvisa as visa
>>> visa.log_to_screen()
>>> rm = visa.ResourceManager()
2024-01-24 10:33:00,321 - pyvisa - DEBUG - No visa library specified, trying to find alternatives.
2024-01-24 10:33:00,321 - pyvisa - DEBUG - Environment variable PYVISA_LIBRARY is unset.
2024-01-24 10:33:00,352 - pyvisa - DEBUG - No user defined configuration
2024-01-24 10:33:00,356 - pyvisa - DEBUG - Automatically found library files: [None, 'C:\\Windows\\System32\\visa32.dll', 'C:\\Windows\\System32\\visa32.dll', None, None]
2024-01-24 10:33:00,357 - pyvisa - DEBUG - No user defined library files
2024-01-24 10:33:00,357 - pyvisa - DEBUG - The IVI implementation available
2024-01-24 10:33:00,357 - pyvisa - DEBUG - No user defined configuration
2024-01-24 10:33:00,361 - pyvisa - DEBUG - Automatically found library files: [None, 'C:\\Windows\\System32\\visa32.dll', 'C:\\Windows\\System32\\visa32.dll', None, None]
2024-01-24 10:33:00,362 - pyvisa - DEBUG - No user defined library files
2024-01-24 10:33:00,413 - pyvisa - DEBUG - Library signatures: 90 ok, 0 failed
2024-01-24 10:33:00,413 - pyvisa - DEBUG - Created library wrapper for C:\Windows\System32\visa32.dll
2024-01-24 10:33:00,488 - pyvisa - DEBUG - viOpenDefaultRM('<ViObject object at 0x01865460>',) -> 0
2024-01-24 10:33:00,488 - pyvisa - DEBUG - Created ResourceManager with session 27214120
>>> print(rm.resource_info('RSIB::169.254.168.15::INSTR', extended=False))
2024-01-24 10:33:51,447 - pyvisa - DEBUG - viParseRsrc(27214120, 'RSIB::169.254.168.15::INSTR', 'c_ushort(6)', 'c_ushort(0)') -> 0
ResourceInfo(interface_type=<InterfaceType.tcpip: 6>, interface_board_number=0, resource_class=None, resource_name=None, alias=None)
>>> int,bla = rm.open_bare_resource('RSIB::169.254.168.15::INSTR')
2024-01-24 10:37:11,725 - pyvisa - DEBUG - viOpen(27214120, 'RSIB::169.254.168.15::INSTR', <AccessModes.no_lock: 0>, 0, '<ViObject object at 0x024426E8>') -> 0
>>> print(rm.visalib.write(int, '*IDN?\n'))
2024-01-24 10:43:19,900 - pyvisa - DEBUG - viWrite(59295856, '*IDN?\n', 6, 'c_ulong(6)') -> 0
(6, <StatusCode.success: 0>)
>>> print(rm.visalib.read(int, 128))
2024-01-24 10:43:42,037 - pyvisa - DEBUG - viRead(59295856, <ctypes.c_char_Array_128 object at 0x024426E8>, 128, 'c_ulong(36)') -> 0
(b'Rohde&Schwarz,ESPI-3,100331/003,2.92', <StatusCode.success: 0>)
```

Maybe you can now help to fully implement it?
Is there a known workarround for using a 64Bit Python again?

**Comment by MatthieuDartiailh** [comment]
Great ! So you can make things look better by specifying a resource class as I first suggested. 

There is no workaround to use a 32 bits dll with a 64 bits Python (and the issue is more general). You could make a 32 bits Python talk to a 64 bits Python using IPC or a socket but that is a rather heavy solution.
