### ISSUE TITLE
[COM] ConnectionRefusedError with pyvisa TCPIP SOCKET & plotly Dash

### ISSUE THREAD

**Issue by kraft-fernwaerme** [pyvisa/pyvisa#818]
A measuring instrument (Ahlborn ALMEMO 2690) connected via RS232 works with pyvisa & plotly Dash (tested simplified python code examples used):

```python
import pyvisa
from pyvisa.constants import StopBits, Parity
import time
from dash import Dash, html, dcc, callback, Output, Input

rm = pyvisa.ResourceManager('@py')
# Ahlborn ALMEMO 2690 over RS232 @ 115200 bd 8N1
measuring_instrument = rm.open_resource('ASRL/dev/ttyS0::INSTR', baud_rate=115200, data_bits=8, parity=Parity.none, stop_bits=StopBits.one)
measuring_instrument.read_termination = '' # required character(s), see manual of measuring_instrument: none required for RS232
measuring_instrument.write_termination = '' # required character(s), see manual of measuring_instrument: none required
measuring_instrument.write('f1G02') # init_string, see manual of measuring_instrument
timer1 = time.time() # time.time() uses float in seconds: 1 = 1 s
cycle_time = 0.5 # measurement cycle time, given in seconds as float value
cycle_time_ms = int(cycle_time * 1000) # measurement cycle time, given in milliseconds (integer)

app = Dash(__name__)
app.layout = html.Div(
    html.Div([
        dcc.Interval(
            id='interval',
            interval = cycle_time_ms, #measurement cycle time, given in milliseconds (integer)
            n_intervals = 0
        ),
        html.Div(id='measurement_instrument_output'),
    ])
)

@app.callback(
    Output(component_id='measurement_instrument_output', component_property='children'),
    [Input(component_id='interval', component_property='n_intervals')]
)

def update(n_intervals):
    measuring_instrument.flush(pyvisa.constants.BufferOperation.discard_read_buffer) # clearing read_buffer, required
    measuring_instrument.write('S1') # send_string, see manual of measuring_instrument
    time.sleep(0.02) # depends on instrument transfer speed
    value0 = measuring_instrument.read(encoding='iso-8859-15') # value0 = send_string, should be neglected
    value1 = measuring_instrument.read(encoding='iso-8859-15') # value1 = response_string, required
    return (value1)

if __name__ == '__main__':
    app.run_server(debug=True)
```

If connection of this measuring instrument is switched to ethernet it works with pyvisa and without plotly Dash:

```python
import pyvisa
import time

rm = pyvisa.ResourceManager('@py')
# Ahlborn ALMEMO 2690 over ethernet @ TCP/IP 192.168.0.240:10001
measuring_instrument = rm.open_resource('TCPIP::192.168.0.240::10001::SOCKET') # TCPIP::192.168.0.240::INSTR doesn't work!
measuring_instrument.read_termination = '\n' # required character(s), see manual of measuring_instrument: \n required for ethernet
measuring_instrument.write_termination = '' # required character(s), see manual of measuring_instrument: none required
measuring_instrument.write('f1G02') # init_string, see manual of measuring_instrument
timer1 = time.time() # time.time() uses float in seconds: 1 = 1 s
cycle_time = 0.5 # measurement cycle time, given in seconds as float value

while True:
    timer2 = time.time()
    diff = timer2 - timer1
    if diff >= cycle_time:
        timer1 = time.time()
        measuring_instrument.flush(pyvisa.constants.BufferOperation.discard_read_buffer) # clearing read_buffer, required
        measuring_instrument.write('S1') # send_string, see manual of measuring_instrument
        time.sleep(0.02) # depends on instrument transfer speed
        value0 = measuring_instrument.read(encoding='iso-8859-15') # value0 = send_string, should be neglected
        value1 = measuring_instrument.read(encoding='iso-8859-15') # value1 = response_string, required
        print(value1)
```
Console shows expected output:

> ;16.04.24 16:25:28.70;20,59;28,78
> ;16.04.24 16:25:29.30;20,6;28,77
> ;16.04.24 16:25:29.60;20,59;28,77
> ;16.04.24 16:25:30.20;20,59;28,77
> ;16.04.24 16:25:30.80;20,59;28,78
> ;16.04.24 16:25:31.10;20,59;28,78
> ;16.04.24 16:25:31.70;20,59;28,77
> ;16.04.24 16:25:32.30;20,59;28,77

… and so on.

But it doesn't work if plotly Dash is added to pyvisa with use of TCPIP SOCKET:

```python
import pyvisa
import time
from dash import Dash, html, dcc, callback, Output, Input

rm = pyvisa.ResourceManager('@py')
# Ahlborn ALMEMO 2690 over ethernet @ TCP/IP 192.168.0.240:10001
measuring_instrument = rm.open_resource('TCPIP::192.168.0.240::10001::SOCKET') # TCPIP::192.168.0.240::INSTR doesn't work!
measuring_instrument.read_termination = '\n' # required character(s), see manual of measuring_instrument: \n required for ethernet
measuring_instrument.write_termination = '' # required character(s), see manual of measuring_instrument: none required
measuring_instrument.write('f1G02') # init_string, see manual of measuring_instrument
timer1 = time.time() # time.time() uses float in seconds: 1 = 1 s
cycle_time = 0.5 # measurement cycle time, given in seconds as float value
cycle_time_ms = int(cycle_time * 1000) # measurement cycle time, given in milliseconds (integer)

app = Dash(__name__)
app.layout = html.Div(
    html.Div([
        dcc.Interval(
            id='interval',
            interval = cycle_time_ms, #measurement cycle time, given in milliseconds (integer)
            n_intervals = 0
        ),
        html.Div(id='measurement_instrument_output'),
    ])
)

@app.callback(
    Output(component_id='measurement_instrument_output', component_property='children'),
    [Input(component_id='interval', component_property='n_intervals')]
)

def update(n_intervals):
    measuring_instrument.flush(pyvisa.constants.BufferOperation.discard_read_buffer) # clearing read_buffer, required
    measuring_instrument.write('S1') # send_string, see manual of measuring_instrument
    time.sleep(0.02) # depends on instrument transfer speed
    value0 = measuring_instrument.read(encoding='iso-8859-15') # value0 = send_string, should be neglected
    value1 = measuring_instrument.read(encoding='iso-8859-15') # value1 = response_string, required
    return (value1)

if __name__ == '__main__':
    app.run_server(debug=True)
```

Console shows error output:

> Dash is running on http://127.0.0.1:8050/
> 
>  * Serving Flask app 'pyVISA-example12'
>  * Debug mode: on
> Traceback (most recent call last):
>   File "/home/user/testing/pyVISA-example12.py", line 10, in <module>
>     measuring_instrument.write('f1G02') # init_string, see manual of measuring_instrument
>   File "/home/user/.local/lib/python3.9/site-packages/pyvisa/resources/messagebased.py", line 197, in write
>     count = self.write_raw(message.encode(enco))
>   File "/home/user/.local/lib/python3.9/site-packages/pyvisa/resources/messagebased.py", line 157, in write_raw
>     return self.visalib.write(self.session, message)[0]
>   File "/home/user/.local/lib/python3.9/site-packages/pyvisa_py/highlevel.py", line 543, in write
>     written, status_code = self.sessions[session].write(data)
>   File "/home/user/.local/lib/python3.9/site-packages/pyvisa_py/tcpip.py", line 1246, in write
>     size = self.interface.send(block)
> ConnectionRefusedError: [Errno 111] Connection refused

What is going wrong here?

Using this code
```python
import pyvisa
import time
from dash import Dash, html, dcc, callback, Output, Input

rm = pyvisa.ResourceManager('@py')
# Ahlborn ALMEMO 2690 over ethernet @ TCP/IP 192.168.0.240:10001
measuring_instrument = rm.open_resource('TCPIP0::192.168.0.240::10001::SOCKET') # TCPIP::192.168.0.240::INSTR doesn't work!
measuring_instrument.read_termination = '\r\n' # required character(s), see manual of measuring_instrument: \r\n required for ethernet
measuring_instrument.write_termination = '' # required character(s), see manual of measuring_instrument: none required
measuring_instrument.write('f1G02') # init_string, see manual of measuring_instrument
time.sleep(1)

# for debugging only
measuring_instrument.flush(pyvisa.constants.BufferOperation.discard_read_buffer) # clearing read_buffer, required
measuring_instrument.write('S1') # send_string, see manual of measuring_instrument
time.sleep(0.02) # depends on instrument transfer speed
value0 = measuring_instrument.read(encoding='iso-8859-15') # value0 = send_string, should be neglected
value1 = measuring_instrument.read(encoding='iso-8859-15') # value1 = response_string, required
print (value1)

cycle_time = 0.5 # measurement cycle time, given in seconds as float value
cycle_time_ms = int(cycle_time * 1000) # measurement cycle time, given in milliseconds (integer)

app = Dash(__name__)
app.layout = html.Div(
    html.Div([
        dcc.Interval(
            id='interval',
            interval = cycle_time_ms, #measurement cycle time, given in milliseconds (integer)
            n_intervals = 0
        ),
        html.Div(id='measurement_instrument_output'),
    ])
)

@app.callback(
    Output(component_id='measurement_instrument_output', component_property='children'),
    [Input(component_id='interval', component_property='n_intervals')]
)

def update(n_intervals):
    measuring_instrument.flush(pyvisa.constants.BufferOperation.discard_read_buffer) # clearing read_buffer, required
    measuring_instrument.write('S1') # send_string, see manual of measuring_instrument
    time.sleep(0.02) # depends on instrument transfer speed
    value0 = measuring_instrument.read(encoding='iso-8859-15') # value0 = send_string, should be neglected
    value1 = measuring_instrument.read(encoding='iso-8859-15') # value1 = response_string, required
    return (value1)

if __name__ == '__main__':
    app.run_server(port=8050, host='0.0.0.0', debug=True)
```
gives following console output:

```
;08.05.24 11:22:15.00;20,69;106,54
Dash is running on http://0.0.0.0:8050/

 * Serving Flask app 'pyVISA-example12'
 * Debug mode: on
Traceback (most recent call last):
  File "/mnt/exfat-data/Messtechnik/python/pyVISA-Ethernet/pyVISA-example12.py", line 10, in <module>
    measuring_instrument.write('f1G02') # init_string, see manual of measuring_instrument
  File "/home/user/.local/lib/python3.9/site-packages/pyvisa/resources/messagebased.py", line 197, in write
    count = self.write_raw(message.encode(enco))
  File "/home/user/.local/lib/python3.9/site-packages/pyvisa/resources/messagebased.py", line 157, in write_raw
    return self.visalib.write(self.session, message)[0]
  File "/home/user/.local/lib/python3.9/site-packages/pyvisa_py/highlevel.py", line 543, in write
    written, status_code = self.sessions[session].write(data)
  File "/home/user/.local/lib/python3.9/site-packages/pyvisa_py/tcpip.py", line 1246, in write
    size = self.interface.send(block)
ConnectionRefusedError: [Errno 111] Connection refused
```

`;08.05.24 11:22:15.00;20,69;106,54`
is expected output of print(value1) and indicates that program runs error-free until startup of Dash.

tcpdump port 10001 gives following console output:

```
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), snapshot length 262144 bytes
12:27:20.739871 IP pc-008.ffi.37168 > localhost.10001: Flags [S], seq 3917895631, win 32120, options [mss 1460,sackOK,TS val 926210130 ecr 0,nop,wscale 7], length 0
12:27:20.740238 IP localhost.10001 > pc-008.ffi.37168: Flags [S.], seq 5024773, ack 3917895632, win 2047, options [mss 1400], length 0
12:27:20.740252 IP pc-008.ffi.37168 > localhost.10001: Flags [.], ack 1, win 32120, length 0
12:27:20.740313 IP pc-008.ffi.37168 > localhost.10001: Flags [P.], seq 1:6, ack 1, win 32120, length 5
12:27:20.751683 IP localhost.10001 > pc-008.ffi.37168: Flags [.], ack 6, win 2047, length 0
12:27:20.849732 IP localhost.10001 > pc-008.ffi.37168: Flags [P.], seq 1:10, ack 6, win 2047, length 9
12:27:20.849739 IP pc-008.ffi.37168 > localhost.10001: Flags [.], ack 10, win 32111, length 0
12:27:20.870643 IP localhost.10001 > pc-008.ffi.37168: Flags [P.], seq 10:32, ack 6, win 2047, length 22
12:27:20.870649 IP pc-008.ffi.37168 > localhost.10001: Flags [.], ack 32, win 32089, length 0
12:27:21.841979 IP pc-008.ffi.37168 > localhost.10001: Flags [P.], seq 6:8, ack 32, win 32089, length 2
12:27:21.846778 IP localhost.10001 > pc-008.ffi.37168: Flags [P.], seq 32:36, ack 8, win 2047, length 4
12:27:21.846800 IP pc-008.ffi.37168 > localhost.10001: Flags [.], ack 36, win 32085, length 0
12:27:21.867866 IP localhost.10001 > pc-008.ffi.37168: Flags [P.], seq 36:73, ack 8, win 2047, length 37
12:27:21.867885 IP pc-008.ffi.37168 > localhost.10001: Flags [.], ack 73, win 32048, length 0
12:27:22.294691 IP pc-008.ffi.37180 > localhost.10001: Flags [S], seq 453407285, win 32120, options [mss 1460,sackOK,TS val 926211685 ecr 0,nop,wscale 7], length 0
12:27:22.294911 IP localhost.10001 > pc-008.ffi.37180: Flags [R.], seq 0, ack 453407286, win 0, length 0
12:27:22.355329 IP pc-008.ffi.37168 > localhost.10001: Flags [F.], seq 8, ack 73, win 32048, length 0
12:27:22.355627 IP localhost.10001 > pc-008.ffi.37168: Flags [F.], seq 73, ack 9, win 2047, length 0
12:27:22.355639 IP pc-008.ffi.37168 > localhost.10001: Flags [.], ack 74, win 32047, length 0
```
This line
`12:27:22.294691 IP pc-008.ffi.37180 > localhost.10001: Flags [S], seq 453407285, win 32120, options [mss 1460,sackOK,TS val 926211685 ecr 0,nop,wscale 7], length 0`
indicates that Dash startup triggers something to try to connect with measuring instrument. This try kills established connection between pyvisa and measuring instrument.

**Comment by kraft-fernwaerme** [comment]
[editorial]:
Meanwhile I've realized that is not an "instrument" issue, but I haven't found any way to remove the "instrument" label from this issue. Please remove it.

**Comment by MatthieuDartiailh** [comment]
My first though was that it may have to do with Plotly running twice the body of your script but I would expect such a thing to also cause a problem with serial communication.  However your latest tcpdump seems to point to the same issue. 

It may hurt performance a bit but could you try to move the connection initialization directly into your callback and use a coontext manager to ensure the connection is closed after each call ?

**Comment by kraft-fernwaerme** [comment]
Following code is the sledgehammer method, but it works:
```python
import pyvisa
import time
from dash import Dash, html, dcc, callback, Output, Input

cycle_time = 0.5 # measurement cycle time, given in seconds as float value
cycle_time_ms = int(cycle_time * 1000) # measurement cycle time, given in milliseconds (integer)

app = Dash(__name__)
app.layout = html.Div(
    html.Div([
        dcc.Interval(
            id='interval',
            interval = cycle_time_ms, #measurement cycle time, given in milliseconds (integer)
            n_intervals = 0
        ),
        html.Div(id='measurement_instrument_output'),
    ])
)

@app.callback(
    Output(component_id='measurement_instrument_output', component_property='children'),
    [Input(component_id='interval', component_property='n_intervals')]
)

def update(n_intervals):
    rm = pyvisa.ResourceManager('@py')
    # Ahlborn ALMEMO 2690 over ethernet @ TCP/IP 192.168.0.240:10001
    measuring_instrument = rm.open_resource('TCPIP0::192.168.0.240::10001::SOCKET') # TCPIP::192.168.0.240::INSTR doesn't work!
    measuring_instrument.read_termination = '\r\n' # required character(s), see manual of measuring_instrument: \r\n required for ethernet
    measuring_instrument.write_termination = '' # required character(s), see manual of measuring_instrument: none required
    measuring_instrument.write('f1G02') # init_string, see manual of measuring_instrument
    time.sleep(0.02) # depends on measuring_instrument transfer speed
    measuring_instrument.flush(pyvisa.constants.BufferOperation.discard_read_buffer) # clearing read_buffer, required
    measuring_instrument.write('S1') # send_string, see manual of measuring_instrument
    time.sleep(0.02) # depends on measuring_instrument transfer speed
    value0 = measuring_instrument.read(encoding='iso-8859-15') # value0 = send_string, should be neglected
    value1 = measuring_instrument.read(encoding='iso-8859-15') # value1 = response_string, required
    measuring_instrument.write('X') # stop data transfer
    rm.close() # close & remove measuring_instrument = TCP/IP socket
    return (value1)

if __name__ == '__main__':
    app.run_server(port=8050, host='0.0.0.0', debug=True)
```
Code given above is not suitable for measurements with very short measurement cycle times due to its large "overhead". Switch to native RS232 connections is highly recommended for measurements with very short measurement cycle times to avoid additional communication overhead because this measuring instrument has a RS232 interface only. Available connecting devices over ethernet, bluetooth or USB are realized with converters to RS232 interface of this measuring instrument. Only USB works fully transparent. pyvisa code for serial connection has to be used, not code for USB! Only `/dev/ttyS` has to be replaced with `/dev/ttyUSB`.

**Comment by MatthieuDartiailh** [comment]
You could also see if Dash has the option to run specific code only on app startup and you could then open the connection a single time
